/**
 * This class is generated by jOOQ
 */
package schema.performance_schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupInstrumentsRecord extends org.jooq.impl.TableRecordImpl<schema.performance_schema.tables.records.SetupInstrumentsRecord> implements org.jooq.Record3<java.lang.String, schema.performance_schema.enums.SetupInstrumentsEnabled, schema.performance_schema.enums.SetupInstrumentsTimed> {

	private static final long serialVersionUID = -1677364671;

	/**
	 * Setter for <code>performance_schema.setup_instruments.NAME</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>performance_schema.setup_instruments.NAME</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>performance_schema.setup_instruments.ENABLED</code>.
	 */
	public void setEnabled(schema.performance_schema.enums.SetupInstrumentsEnabled value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>performance_schema.setup_instruments.ENABLED</code>.
	 */
	public schema.performance_schema.enums.SetupInstrumentsEnabled getEnabled() {
		return (schema.performance_schema.enums.SetupInstrumentsEnabled) getValue(1);
	}

	/**
	 * Setter for <code>performance_schema.setup_instruments.TIMED</code>.
	 */
	public void setTimed(schema.performance_schema.enums.SetupInstrumentsTimed value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>performance_schema.setup_instruments.TIMED</code>.
	 */
	public schema.performance_schema.enums.SetupInstrumentsTimed getTimed() {
		return (schema.performance_schema.enums.SetupInstrumentsTimed) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, schema.performance_schema.enums.SetupInstrumentsEnabled, schema.performance_schema.enums.SetupInstrumentsTimed> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, schema.performance_schema.enums.SetupInstrumentsEnabled, schema.performance_schema.enums.SetupInstrumentsTimed> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.performance_schema.tables.SetupInstruments.SETUP_INSTRUMENTS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.performance_schema.enums.SetupInstrumentsEnabled> field2() {
		return schema.performance_schema.tables.SetupInstruments.SETUP_INSTRUMENTS.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.performance_schema.enums.SetupInstrumentsTimed> field3() {
		return schema.performance_schema.tables.SetupInstruments.SETUP_INSTRUMENTS.TIMED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.performance_schema.enums.SetupInstrumentsEnabled value2() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.performance_schema.enums.SetupInstrumentsTimed value3() {
		return getTimed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetupInstrumentsRecord value1(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetupInstrumentsRecord value2(schema.performance_schema.enums.SetupInstrumentsEnabled value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetupInstrumentsRecord value3(schema.performance_schema.enums.SetupInstrumentsTimed value) {
		setTimed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetupInstrumentsRecord values(java.lang.String value1, schema.performance_schema.enums.SetupInstrumentsEnabled value2, schema.performance_schema.enums.SetupInstrumentsTimed value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SetupInstrumentsRecord
	 */
	public SetupInstrumentsRecord() {
		super(schema.performance_schema.tables.SetupInstruments.SETUP_INSTRUMENTS);
	}

	/**
	 * Create a detached, initialised SetupInstrumentsRecord
	 */
	public SetupInstrumentsRecord(java.lang.String name, schema.performance_schema.enums.SetupInstrumentsEnabled enabled, schema.performance_schema.enums.SetupInstrumentsTimed timed) {
		super(schema.performance_schema.tables.SetupInstruments.SETUP_INSTRUMENTS);

		setValue(0, name);
		setValue(1, enabled);
		setValue(2, timed);
	}
}
