/**
 * This class is generated by jOOQ
 */
package schema.performance_schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupTimersRecord extends org.jooq.impl.TableRecordImpl<schema.performance_schema.tables.records.SetupTimersRecord> implements org.jooq.Record2<java.lang.String, schema.performance_schema.enums.SetupTimersTimerName> {

	private static final long serialVersionUID = 1375151922;

	/**
	 * Setter for <code>performance_schema.setup_timers.NAME</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>performance_schema.setup_timers.NAME</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>performance_schema.setup_timers.TIMER_NAME</code>.
	 */
	public void setTimerName(schema.performance_schema.enums.SetupTimersTimerName value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>performance_schema.setup_timers.TIMER_NAME</code>.
	 */
	public schema.performance_schema.enums.SetupTimersTimerName getTimerName() {
		return (schema.performance_schema.enums.SetupTimersTimerName) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, schema.performance_schema.enums.SetupTimersTimerName> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, schema.performance_schema.enums.SetupTimersTimerName> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.performance_schema.tables.SetupTimers.SETUP_TIMERS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.performance_schema.enums.SetupTimersTimerName> field2() {
		return schema.performance_schema.tables.SetupTimers.SETUP_TIMERS.TIMER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.performance_schema.enums.SetupTimersTimerName value2() {
		return getTimerName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetupTimersRecord value1(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetupTimersRecord value2(schema.performance_schema.enums.SetupTimersTimerName value) {
		setTimerName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetupTimersRecord values(java.lang.String value1, schema.performance_schema.enums.SetupTimersTimerName value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SetupTimersRecord
	 */
	public SetupTimersRecord() {
		super(schema.performance_schema.tables.SetupTimers.SETUP_TIMERS);
	}

	/**
	 * Create a detached, initialised SetupTimersRecord
	 */
	public SetupTimersRecord(java.lang.String name, schema.performance_schema.enums.SetupTimersTimerName timerName) {
		super(schema.performance_schema.tables.SetupTimers.SETUP_TIMERS);

		setValue(0, name);
		setValue(1, timerName);
	}
}
