/**
 * This class is generated by jOOQ
 */
package cleandb.cleanrawdata.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConstructRecord extends org.jooq.impl.UpdatableRecordImpl<cleandb.cleanrawdata.tables.records.ConstructRecord> implements org.jooq.Record8<byte[], java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long, byte[]> {

	private static final long serialVersionUID = -429903852;

	/**
	 * Setter for <code>CleanRawData.Construct.ConstructID</code>.
	 */
	public void setConstructid(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>CleanRawData.Construct.ConstructID</code>.
	 */
	public byte[] getConstructid() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>CleanRawData.Construct.SourceConstructID</code>.
	 */
	public void setSourceconstructid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>CleanRawData.Construct.SourceConstructID</code>.
	 */
	public java.lang.String getSourceconstructid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>CleanRawData.Construct.ConstructType</code>.
	 */
	public void setConstructtype(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>CleanRawData.Construct.ConstructType</code>.
	 */
	public java.lang.String getConstructtype() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>CleanRawData.Construct.ConstructName</code>.
	 */
	public void setConstructname(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>CleanRawData.Construct.ConstructName</code>.
	 */
	public java.lang.String getConstructname() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>CleanRawData.Construct.StartTime</code>.
	 */
	public void setStarttime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>CleanRawData.Construct.StartTime</code>.
	 */
	public java.sql.Timestamp getStarttime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>CleanRawData.Construct.EndTime</code>.
	 */
	public void setEndtime(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>CleanRawData.Construct.EndTime</code>.
	 */
	public java.sql.Timestamp getEndtime() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>CleanRawData.Construct.Duration</code>.
	 */
	public void setDuration(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>CleanRawData.Construct.Duration</code>.
	 */
	public java.lang.Long getDuration() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>CleanRawData.Construct.ProcessInstanceID</code>.
	 */
	public void setProcessinstanceid(byte[] value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>CleanRawData.Construct.ProcessInstanceID</code>.
	 */
	public byte[] getProcessinstanceid() {
		return (byte[]) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<byte[]> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<byte[], java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long, byte[]> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<byte[], java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long, byte[]> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return cleandb.cleanrawdata.tables.Construct.CONSTRUCT.CONSTRUCTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cleandb.cleanrawdata.tables.Construct.CONSTRUCT.SOURCECONSTRUCTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return cleandb.cleanrawdata.tables.Construct.CONSTRUCT.CONSTRUCTTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return cleandb.cleanrawdata.tables.Construct.CONSTRUCT.CONSTRUCTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return cleandb.cleanrawdata.tables.Construct.CONSTRUCT.STARTTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return cleandb.cleanrawdata.tables.Construct.CONSTRUCT.ENDTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return cleandb.cleanrawdata.tables.Construct.CONSTRUCT.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field8() {
		return cleandb.cleanrawdata.tables.Construct.CONSTRUCT.PROCESSINSTANCEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getConstructid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSourceconstructid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getConstructtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getConstructname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getStarttime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getEndtime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value8() {
		return getProcessinstanceid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord value1(byte[] value) {
		setConstructid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord value2(java.lang.String value) {
		setSourceconstructid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord value3(java.lang.String value) {
		setConstructtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord value4(java.lang.String value) {
		setConstructname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord value5(java.sql.Timestamp value) {
		setStarttime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord value6(java.sql.Timestamp value) {
		setEndtime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord value7(java.lang.Long value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord value8(byte[] value) {
		setProcessinstanceid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConstructRecord values(byte[] value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.sql.Timestamp value5, java.sql.Timestamp value6, java.lang.Long value7, byte[] value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ConstructRecord
	 */
	public ConstructRecord() {
		super(cleandb.cleanrawdata.tables.Construct.CONSTRUCT);
	}

	/**
	 * Create a detached, initialised ConstructRecord
	 */
	public ConstructRecord(byte[] constructid, java.lang.String sourceconstructid, java.lang.String constructtype, java.lang.String constructname, java.sql.Timestamp starttime, java.sql.Timestamp endtime, java.lang.Long duration, byte[] processinstanceid) {
		super(cleandb.cleanrawdata.tables.Construct.CONSTRUCT);

		setValue(0, constructid);
		setValue(1, sourceconstructid);
		setValue(2, constructtype);
		setValue(3, constructname);
		setValue(4, starttime);
		setValue(5, endtime);
		setValue(6, duration);
		setValue(7, processinstanceid);
	}
}
