/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiTaskinst extends org.jooq.impl.TableImpl<schema.process_engine.tables.records.ActHiTaskinstRecord> {

	private static final long serialVersionUID = -477092330;

	/**
	 * The reference instance of <code>process-engine.ACT_HI_TASKINST</code>
	 */
	public static final schema.process_engine.tables.ActHiTaskinst ACT_HI_TASKINST = new schema.process_engine.tables.ActHiTaskinst();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.process_engine.tables.records.ActHiTaskinstRecord> getRecordType() {
		return schema.process_engine.tables.records.ActHiTaskinstRecord.class;
	}

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> ID_ = createField("ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.PROC_DEF_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> PROC_DEF_ID_ = createField("PROC_DEF_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.TASK_DEF_KEY_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> TASK_DEF_KEY_ = createField("TASK_DEF_KEY_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.PROC_INST_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> PROC_INST_ID_ = createField("PROC_INST_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.EXECUTION_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> EXECUTION_ID_ = createField("EXECUTION_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.ACT_INST_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> ACT_INST_ID_ = createField("ACT_INST_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.NAME_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> NAME_ = createField("NAME_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.PARENT_TASK_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> PARENT_TASK_ID_ = createField("PARENT_TASK_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.DESCRIPTION_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> DESCRIPTION_ = createField("DESCRIPTION_", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.OWNER_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> OWNER_ = createField("OWNER_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.ASSIGNEE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> ASSIGNEE_ = createField("ASSIGNEE_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.START_TIME_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.sql.Timestamp> START_TIME_ = createField("START_TIME_", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.END_TIME_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.sql.Timestamp> END_TIME_ = createField("END_TIME_", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.DURATION_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.Long> DURATION_ = createField("DURATION_", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.DELETE_REASON_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.String> DELETE_REASON_ = createField("DELETE_REASON_", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.PRIORITY_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.lang.Integer> PRIORITY_ = createField("PRIORITY_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.DUE_DATE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.sql.Timestamp> DUE_DATE_ = createField("DUE_DATE_", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>process-engine.ACT_HI_TASKINST.FOLLOW_UP_DATE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiTaskinstRecord, java.sql.Timestamp> FOLLOW_UP_DATE_ = createField("FOLLOW_UP_DATE_", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>process-engine.ACT_HI_TASKINST</code> table reference
	 */
	public ActHiTaskinst() {
		this("ACT_HI_TASKINST", null);
	}

	/**
	 * Create an aliased <code>process-engine.ACT_HI_TASKINST</code> table reference
	 */
	public ActHiTaskinst(java.lang.String alias) {
		this(alias, schema.process_engine.tables.ActHiTaskinst.ACT_HI_TASKINST);
	}

	private ActHiTaskinst(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActHiTaskinstRecord> aliased) {
		this(alias, aliased, null);
	}

	private ActHiTaskinst(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActHiTaskinstRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.process_engine.Process_engine.PROCESS_ENGINE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<schema.process_engine.tables.records.ActHiTaskinstRecord> getPrimaryKey() {
		return schema.process_engine.Keys.KEY_ACT_HI_TASKINST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<schema.process_engine.tables.records.ActHiTaskinstRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<schema.process_engine.tables.records.ActHiTaskinstRecord>>asList(schema.process_engine.Keys.KEY_ACT_HI_TASKINST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.process_engine.tables.ActHiTaskinst as(java.lang.String alias) {
		return new schema.process_engine.tables.ActHiTaskinst(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.process_engine.tables.ActHiTaskinst rename(java.lang.String name) {
		return new schema.process_engine.tables.ActHiTaskinst(name, null);
	}
}
