/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiAttachment extends org.jooq.impl.TableImpl<schema.process_engine.tables.records.ActHiAttachmentRecord> {

	private static final long serialVersionUID = 340517034;

	/**
	 * The reference instance of <code>process-engine.ACT_HI_ATTACHMENT</code>
	 */
	public static final schema.process_engine.tables.ActHiAttachment ACT_HI_ATTACHMENT = new schema.process_engine.tables.ActHiAttachment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.process_engine.tables.records.ActHiAttachmentRecord> getRecordType() {
		return schema.process_engine.tables.records.ActHiAttachmentRecord.class;
	}

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> ID_ = createField("ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.REV_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.Integer> REV_ = createField("REV_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.USER_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> USER_ID_ = createField("USER_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.NAME_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> NAME_ = createField("NAME_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.DESCRIPTION_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> DESCRIPTION_ = createField("DESCRIPTION_", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.TYPE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> TYPE_ = createField("TYPE_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.TASK_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> TASK_ID_ = createField("TASK_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.PROC_INST_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> PROC_INST_ID_ = createField("PROC_INST_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.URL_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> URL_ = createField("URL_", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>process-engine.ACT_HI_ATTACHMENT.CONTENT_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActHiAttachmentRecord, java.lang.String> CONTENT_ID_ = createField("CONTENT_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * Create a <code>process-engine.ACT_HI_ATTACHMENT</code> table reference
	 */
	public ActHiAttachment() {
		this("ACT_HI_ATTACHMENT", null);
	}

	/**
	 * Create an aliased <code>process-engine.ACT_HI_ATTACHMENT</code> table reference
	 */
	public ActHiAttachment(java.lang.String alias) {
		this(alias, schema.process_engine.tables.ActHiAttachment.ACT_HI_ATTACHMENT);
	}

	private ActHiAttachment(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActHiAttachmentRecord> aliased) {
		this(alias, aliased, null);
	}

	private ActHiAttachment(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActHiAttachmentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.process_engine.Process_engine.PROCESS_ENGINE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<schema.process_engine.tables.records.ActHiAttachmentRecord> getPrimaryKey() {
		return schema.process_engine.Keys.KEY_ACT_HI_ATTACHMENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<schema.process_engine.tables.records.ActHiAttachmentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<schema.process_engine.tables.records.ActHiAttachmentRecord>>asList(schema.process_engine.Keys.KEY_ACT_HI_ATTACHMENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.process_engine.tables.ActHiAttachment as(java.lang.String alias) {
		return new schema.process_engine.tables.ActHiAttachment(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.process_engine.tables.ActHiAttachment rename(java.lang.String name) {
		return new schema.process_engine.tables.ActHiAttachment(name, null);
	}
}
