/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuExecution extends org.jooq.impl.TableImpl<schema.process_engine.tables.records.ActRuExecutionRecord> {

	private static final long serialVersionUID = -676150064;

	/**
	 * The reference instance of <code>process-engine.ACT_RU_EXECUTION</code>
	 */
	public static final schema.process_engine.tables.ActRuExecution ACT_RU_EXECUTION = new schema.process_engine.tables.ActRuExecution();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.process_engine.tables.records.ActRuExecutionRecord> getRecordType() {
		return schema.process_engine.tables.records.ActRuExecutionRecord.class;
	}

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> ID_ = createField("ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.REV_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.Integer> REV_ = createField("REV_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.PROC_INST_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> PROC_INST_ID_ = createField("PROC_INST_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.BUSINESS_KEY_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> BUSINESS_KEY_ = createField("BUSINESS_KEY_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.PARENT_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> PARENT_ID_ = createField("PARENT_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.PROC_DEF_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> PROC_DEF_ID_ = createField("PROC_DEF_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.SUPER_EXEC_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> SUPER_EXEC_ = createField("SUPER_EXEC_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.SUPER_CASE_EXEC_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> SUPER_CASE_EXEC_ = createField("SUPER_CASE_EXEC_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.CASE_INST_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> CASE_INST_ID_ = createField("CASE_INST_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.ACT_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> ACT_ID_ = createField("ACT_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.ACT_INST_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.String> ACT_INST_ID_ = createField("ACT_INST_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.IS_ACTIVE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.Byte> IS_ACTIVE_ = createField("IS_ACTIVE_", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.IS_CONCURRENT_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.Byte> IS_CONCURRENT_ = createField("IS_CONCURRENT_", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.IS_SCOPE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.Byte> IS_SCOPE_ = createField("IS_SCOPE_", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.IS_EVENT_SCOPE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.Byte> IS_EVENT_SCOPE_ = createField("IS_EVENT_SCOPE_", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.SUSPENSION_STATE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.Integer> SUSPENSION_STATE_ = createField("SUSPENSION_STATE_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_EXECUTION.CACHED_ENT_STATE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuExecutionRecord, java.lang.Integer> CACHED_ENT_STATE_ = createField("CACHED_ENT_STATE_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>process-engine.ACT_RU_EXECUTION</code> table reference
	 */
	public ActRuExecution() {
		this("ACT_RU_EXECUTION", null);
	}

	/**
	 * Create an aliased <code>process-engine.ACT_RU_EXECUTION</code> table reference
	 */
	public ActRuExecution(java.lang.String alias) {
		this(alias, schema.process_engine.tables.ActRuExecution.ACT_RU_EXECUTION);
	}

	private ActRuExecution(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActRuExecutionRecord> aliased) {
		this(alias, aliased, null);
	}

	private ActRuExecution(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActRuExecutionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.process_engine.Process_engine.PROCESS_ENGINE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<schema.process_engine.tables.records.ActRuExecutionRecord> getPrimaryKey() {
		return schema.process_engine.Keys.KEY_ACT_RU_EXECUTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<schema.process_engine.tables.records.ActRuExecutionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<schema.process_engine.tables.records.ActRuExecutionRecord>>asList(schema.process_engine.Keys.KEY_ACT_RU_EXECUTION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<schema.process_engine.tables.records.ActRuExecutionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<schema.process_engine.tables.records.ActRuExecutionRecord, ?>>asList(schema.process_engine.Keys.ACT_FK_EXE_PROCINST, schema.process_engine.Keys.ACT_FK_EXE_PARENT, schema.process_engine.Keys.ACT_FK_EXE_PROCDEF, schema.process_engine.Keys.ACT_FK_EXE_SUPER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.process_engine.tables.ActRuExecution as(java.lang.String alias) {
		return new schema.process_engine.tables.ActRuExecution(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.process_engine.tables.ActRuExecution rename(java.lang.String name) {
		return new schema.process_engine.tables.ActRuExecution(name, null);
	}
}
