/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReCaseDef extends org.jooq.impl.TableImpl<schema.process_engine.tables.records.ActReCaseDefRecord> {

	private static final long serialVersionUID = 84089748;

	/**
	 * The reference instance of <code>process-engine.ACT_RE_CASE_DEF</code>
	 */
	public static final schema.process_engine.tables.ActReCaseDef ACT_RE_CASE_DEF = new schema.process_engine.tables.ActReCaseDef();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.process_engine.tables.records.ActReCaseDefRecord> getRecordType() {
		return schema.process_engine.tables.records.ActReCaseDefRecord.class;
	}

	/**
	 * The column <code>process-engine.ACT_RE_CASE_DEF.ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActReCaseDefRecord, java.lang.String> ID_ = createField("ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>process-engine.ACT_RE_CASE_DEF.REV_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActReCaseDefRecord, java.lang.Integer> REV_ = createField("REV_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>process-engine.ACT_RE_CASE_DEF.CATEGORY_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActReCaseDefRecord, java.lang.String> CATEGORY_ = createField("CATEGORY_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_RE_CASE_DEF.NAME_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActReCaseDefRecord, java.lang.String> NAME_ = createField("NAME_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_RE_CASE_DEF.KEY_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActReCaseDefRecord, java.lang.String> KEY_ = createField("KEY_", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>process-engine.ACT_RE_CASE_DEF.VERSION_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActReCaseDefRecord, java.lang.Integer> VERSION_ = createField("VERSION_", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>process-engine.ACT_RE_CASE_DEF.DEPLOYMENT_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActReCaseDefRecord, java.lang.String> DEPLOYMENT_ID_ = createField("DEPLOYMENT_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RE_CASE_DEF.RESOURCE_NAME_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActReCaseDefRecord, java.lang.String> RESOURCE_NAME_ = createField("RESOURCE_NAME_", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * Create a <code>process-engine.ACT_RE_CASE_DEF</code> table reference
	 */
	public ActReCaseDef() {
		this("ACT_RE_CASE_DEF", null);
	}

	/**
	 * Create an aliased <code>process-engine.ACT_RE_CASE_DEF</code> table reference
	 */
	public ActReCaseDef(java.lang.String alias) {
		this(alias, schema.process_engine.tables.ActReCaseDef.ACT_RE_CASE_DEF);
	}

	private ActReCaseDef(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActReCaseDefRecord> aliased) {
		this(alias, aliased, null);
	}

	private ActReCaseDef(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActReCaseDefRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.process_engine.Process_engine.PROCESS_ENGINE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<schema.process_engine.tables.records.ActReCaseDefRecord> getPrimaryKey() {
		return schema.process_engine.Keys.KEY_ACT_RE_CASE_DEF_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<schema.process_engine.tables.records.ActReCaseDefRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<schema.process_engine.tables.records.ActReCaseDefRecord>>asList(schema.process_engine.Keys.KEY_ACT_RE_CASE_DEF_PRIMARY, schema.process_engine.Keys.KEY_ACT_RE_CASE_DEF_ACT_UNIQ_CASE_DEF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.process_engine.tables.ActReCaseDef as(java.lang.String alias) {
		return new schema.process_engine.tables.ActReCaseDef(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.process_engine.tables.ActReCaseDef rename(java.lang.String name) {
		return new schema.process_engine.tables.ActReCaseDef(name, null);
	}
}
