/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuTask extends org.jooq.impl.TableImpl<schema.process_engine.tables.records.ActRuTaskRecord> {

	private static final long serialVersionUID = 58617110;

	/**
	 * The reference instance of <code>process-engine.ACT_RU_TASK</code>
	 */
	public static final schema.process_engine.tables.ActRuTask ACT_RU_TASK = new schema.process_engine.tables.ActRuTask();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.process_engine.tables.records.ActRuTaskRecord> getRecordType() {
		return schema.process_engine.tables.records.ActRuTaskRecord.class;
	}

	/**
	 * The column <code>process-engine.ACT_RU_TASK.ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> ID_ = createField("ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.REV_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.Integer> REV_ = createField("REV_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.EXECUTION_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> EXECUTION_ID_ = createField("EXECUTION_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.PROC_INST_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> PROC_INST_ID_ = createField("PROC_INST_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.PROC_DEF_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> PROC_DEF_ID_ = createField("PROC_DEF_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.CASE_EXECUTION_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> CASE_EXECUTION_ID_ = createField("CASE_EXECUTION_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.CASE_INST_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> CASE_INST_ID_ = createField("CASE_INST_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.CASE_DEF_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> CASE_DEF_ID_ = createField("CASE_DEF_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.NAME_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> NAME_ = createField("NAME_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.PARENT_TASK_ID_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> PARENT_TASK_ID_ = createField("PARENT_TASK_ID_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.DESCRIPTION_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> DESCRIPTION_ = createField("DESCRIPTION_", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.TASK_DEF_KEY_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> TASK_DEF_KEY_ = createField("TASK_DEF_KEY_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.OWNER_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> OWNER_ = createField("OWNER_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.ASSIGNEE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> ASSIGNEE_ = createField("ASSIGNEE_", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.DELEGATION_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.String> DELEGATION_ = createField("DELEGATION_", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.PRIORITY_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.Integer> PRIORITY_ = createField("PRIORITY_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.CREATE_TIME_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.sql.Timestamp> CREATE_TIME_ = createField("CREATE_TIME_", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.DUE_DATE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.sql.Timestamp> DUE_DATE_ = createField("DUE_DATE_", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.FOLLOW_UP_DATE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.sql.Timestamp> FOLLOW_UP_DATE_ = createField("FOLLOW_UP_DATE_", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>process-engine.ACT_RU_TASK.SUSPENSION_STATE_</code>.
	 */
	public final org.jooq.TableField<schema.process_engine.tables.records.ActRuTaskRecord, java.lang.Integer> SUSPENSION_STATE_ = createField("SUSPENSION_STATE_", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>process-engine.ACT_RU_TASK</code> table reference
	 */
	public ActRuTask() {
		this("ACT_RU_TASK", null);
	}

	/**
	 * Create an aliased <code>process-engine.ACT_RU_TASK</code> table reference
	 */
	public ActRuTask(java.lang.String alias) {
		this(alias, schema.process_engine.tables.ActRuTask.ACT_RU_TASK);
	}

	private ActRuTask(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActRuTaskRecord> aliased) {
		this(alias, aliased, null);
	}

	private ActRuTask(java.lang.String alias, org.jooq.Table<schema.process_engine.tables.records.ActRuTaskRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.process_engine.Process_engine.PROCESS_ENGINE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<schema.process_engine.tables.records.ActRuTaskRecord> getPrimaryKey() {
		return schema.process_engine.Keys.KEY_ACT_RU_TASK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<schema.process_engine.tables.records.ActRuTaskRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<schema.process_engine.tables.records.ActRuTaskRecord>>asList(schema.process_engine.Keys.KEY_ACT_RU_TASK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<schema.process_engine.tables.records.ActRuTaskRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<schema.process_engine.tables.records.ActRuTaskRecord, ?>>asList(schema.process_engine.Keys.ACT_FK_TASK_EXE, schema.process_engine.Keys.ACT_FK_TASK_PROCINST, schema.process_engine.Keys.ACT_FK_TASK_PROCDEF, schema.process_engine.Keys.ACT_FK_TASK_CASE_EXE, schema.process_engine.Keys.ACT_FK_TASK_CASE_DEF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.process_engine.tables.ActRuTask as(java.lang.String alias) {
		return new schema.process_engine.tables.ActRuTask(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.process_engine.tables.ActRuTask rename(java.lang.String name) {
		return new schema.process_engine.tables.ActRuTask(name, null);
	}
}
