/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActGeBytearrayRecord extends org.jooq.impl.UpdatableRecordImpl<schema.process_engine.tables.records.ActGeBytearrayRecord> implements org.jooq.Record6<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, byte[], java.lang.Byte> {

	private static final long serialVersionUID = -1983829628;

	/**
	 * Setter for <code>process-engine.ACT_GE_BYTEARRAY.ID_</code>.
	 */
	public void setId_(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_GE_BYTEARRAY.ID_</code>.
	 */
	public java.lang.String getId_() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>process-engine.ACT_GE_BYTEARRAY.REV_</code>.
	 */
	public void setRev_(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_GE_BYTEARRAY.REV_</code>.
	 */
	public java.lang.Integer getRev_() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>process-engine.ACT_GE_BYTEARRAY.NAME_</code>.
	 */
	public void setName_(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_GE_BYTEARRAY.NAME_</code>.
	 */
	public java.lang.String getName_() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>process-engine.ACT_GE_BYTEARRAY.DEPLOYMENT_ID_</code>.
	 */
	public void setDeploymentId_(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_GE_BYTEARRAY.DEPLOYMENT_ID_</code>.
	 */
	public java.lang.String getDeploymentId_() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>process-engine.ACT_GE_BYTEARRAY.BYTES_</code>.
	 */
	public void setBytes_(byte[] value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_GE_BYTEARRAY.BYTES_</code>.
	 */
	public byte[] getBytes_() {
		return (byte[]) getValue(4);
	}

	/**
	 * Setter for <code>process-engine.ACT_GE_BYTEARRAY.GENERATED_</code>.
	 */
	public void setGenerated_(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_GE_BYTEARRAY.GENERATED_</code>.
	 */
	public java.lang.Byte getGenerated_() {
		return (java.lang.Byte) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, byte[], java.lang.Byte> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, byte[], java.lang.Byte> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.process_engine.tables.ActGeBytearray.ACT_GE_BYTEARRAY.ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return schema.process_engine.tables.ActGeBytearray.ACT_GE_BYTEARRAY.REV_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return schema.process_engine.tables.ActGeBytearray.ACT_GE_BYTEARRAY.NAME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return schema.process_engine.tables.ActGeBytearray.ACT_GE_BYTEARRAY.DEPLOYMENT_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field5() {
		return schema.process_engine.tables.ActGeBytearray.ACT_GE_BYTEARRAY.BYTES_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field6() {
		return schema.process_engine.tables.ActGeBytearray.ACT_GE_BYTEARRAY.GENERATED_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRev_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDeploymentId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value5() {
		return getBytes_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value6() {
		return getGenerated_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActGeBytearrayRecord value1(java.lang.String value) {
		setId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActGeBytearrayRecord value2(java.lang.Integer value) {
		setRev_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActGeBytearrayRecord value3(java.lang.String value) {
		setName_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActGeBytearrayRecord value4(java.lang.String value) {
		setDeploymentId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActGeBytearrayRecord value5(byte[] value) {
		setBytes_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActGeBytearrayRecord value6(java.lang.Byte value) {
		setGenerated_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActGeBytearrayRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, byte[] value5, java.lang.Byte value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActGeBytearrayRecord
	 */
	public ActGeBytearrayRecord() {
		super(schema.process_engine.tables.ActGeBytearray.ACT_GE_BYTEARRAY);
	}

	/**
	 * Create a detached, initialised ActGeBytearrayRecord
	 */
	public ActGeBytearrayRecord(java.lang.String id_, java.lang.Integer rev_, java.lang.String name_, java.lang.String deploymentId_, byte[] bytes_, java.lang.Byte generated_) {
		super(schema.process_engine.tables.ActGeBytearray.ACT_GE_BYTEARRAY);

		setValue(0, id_);
		setValue(1, rev_);
		setValue(2, name_);
		setValue(3, deploymentId_);
		setValue(4, bytes_);
		setValue(5, generated_);
	}
}
