/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiDetailRecord extends org.jooq.impl.UpdatableRecordImpl<schema.process_engine.tables.records.ActHiDetailRecord> implements org.jooq.Record16<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Double, java.lang.Long, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1359074527;

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.ID_</code>.
	 */
	public void setId_(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.ID_</code>.
	 */
	public java.lang.String getId_() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.TYPE_</code>.
	 */
	public void setType_(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.TYPE_</code>.
	 */
	public java.lang.String getType_() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.PROC_INST_ID_</code>.
	 */
	public void setProcInstId_(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.PROC_INST_ID_</code>.
	 */
	public java.lang.String getProcInstId_() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.EXECUTION_ID_</code>.
	 */
	public void setExecutionId_(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.EXECUTION_ID_</code>.
	 */
	public java.lang.String getExecutionId_() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.TASK_ID_</code>.
	 */
	public void setTaskId_(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.TASK_ID_</code>.
	 */
	public java.lang.String getTaskId_() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.ACT_INST_ID_</code>.
	 */
	public void setActInstId_(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.ACT_INST_ID_</code>.
	 */
	public java.lang.String getActInstId_() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.VAR_INST_ID_</code>.
	 */
	public void setVarInstId_(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.VAR_INST_ID_</code>.
	 */
	public java.lang.String getVarInstId_() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.NAME_</code>.
	 */
	public void setName_(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.NAME_</code>.
	 */
	public java.lang.String getName_() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.VAR_TYPE_</code>.
	 */
	public void setVarType_(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.VAR_TYPE_</code>.
	 */
	public java.lang.String getVarType_() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.REV_</code>.
	 */
	public void setRev_(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.REV_</code>.
	 */
	public java.lang.Integer getRev_() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.TIME_</code>.
	 */
	public void setTime_(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.TIME_</code>.
	 */
	public java.sql.Timestamp getTime_() {
		return (java.sql.Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.BYTEARRAY_ID_</code>.
	 */
	public void setBytearrayId_(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.BYTEARRAY_ID_</code>.
	 */
	public java.lang.String getBytearrayId_() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.DOUBLE_</code>.
	 */
	public void setDouble_(java.lang.Double value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.DOUBLE_</code>.
	 */
	public java.lang.Double getDouble_() {
		return (java.lang.Double) getValue(12);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.LONG_</code>.
	 */
	public void setLong_(java.lang.Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.LONG_</code>.
	 */
	public java.lang.Long getLong_() {
		return (java.lang.Long) getValue(13);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.TEXT_</code>.
	 */
	public void setText_(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.TEXT_</code>.
	 */
	public java.lang.String getText_() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_DETAIL.TEXT2_</code>.
	 */
	public void setText2_(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_DETAIL.TEXT2_</code>.
	 */
	public java.lang.String getText2_() {
		return (java.lang.String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Double, java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Double, java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.PROC_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.EXECUTION_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.TASK_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.ACT_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.VAR_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.NAME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.VAR_TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.REV_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.TIME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.BYTEARRAY_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field13() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.DOUBLE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field14() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.LONG_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.TEXT_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL.TEXT2_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getType_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getProcInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getExecutionId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTaskId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getActInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getVarInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getName_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getVarType_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getRev_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getTime_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getBytearrayId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value13() {
		return getDouble_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value14() {
		return getLong_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getText_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getText2_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value1(java.lang.String value) {
		setId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value2(java.lang.String value) {
		setType_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value3(java.lang.String value) {
		setProcInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value4(java.lang.String value) {
		setExecutionId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value5(java.lang.String value) {
		setTaskId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value6(java.lang.String value) {
		setActInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value7(java.lang.String value) {
		setVarInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value8(java.lang.String value) {
		setName_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value9(java.lang.String value) {
		setVarType_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value10(java.lang.Integer value) {
		setRev_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value11(java.sql.Timestamp value) {
		setTime_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value12(java.lang.String value) {
		setBytearrayId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value13(java.lang.Double value) {
		setDouble_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value14(java.lang.Long value) {
		setLong_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value15(java.lang.String value) {
		setText_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord value16(java.lang.String value) {
		setText2_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiDetailRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.Integer value10, java.sql.Timestamp value11, java.lang.String value12, java.lang.Double value13, java.lang.Long value14, java.lang.String value15, java.lang.String value16) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActHiDetailRecord
	 */
	public ActHiDetailRecord() {
		super(schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL);
	}

	/**
	 * Create a detached, initialised ActHiDetailRecord
	 */
	public ActHiDetailRecord(java.lang.String id_, java.lang.String type_, java.lang.String procInstId_, java.lang.String executionId_, java.lang.String taskId_, java.lang.String actInstId_, java.lang.String varInstId_, java.lang.String name_, java.lang.String varType_, java.lang.Integer rev_, java.sql.Timestamp time_, java.lang.String bytearrayId_, java.lang.Double double_, java.lang.Long long_, java.lang.String text_, java.lang.String text2_) {
		super(schema.process_engine.tables.ActHiDetail.ACT_HI_DETAIL);

		setValue(0, id_);
		setValue(1, type_);
		setValue(2, procInstId_);
		setValue(3, executionId_);
		setValue(4, taskId_);
		setValue(5, actInstId_);
		setValue(6, varInstId_);
		setValue(7, name_);
		setValue(8, varType_);
		setValue(9, rev_);
		setValue(10, time_);
		setValue(11, bytearrayId_);
		setValue(12, double_);
		setValue(13, long_);
		setValue(14, text_);
		setValue(15, text2_);
	}
}
