/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiActinstRecord extends org.jooq.impl.UpdatableRecordImpl<schema.process_engine.tables.records.ActHiActinstRecord> implements org.jooq.Record15<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long, java.lang.Integer> {

	private static final long serialVersionUID = -1822195140;

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.ID_</code>.
	 */
	public void setId_(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.ID_</code>.
	 */
	public java.lang.String getId_() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.PARENT_ACT_INST_ID_</code>.
	 */
	public void setParentActInstId_(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.PARENT_ACT_INST_ID_</code>.
	 */
	public java.lang.String getParentActInstId_() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.PROC_DEF_ID_</code>.
	 */
	public void setProcDefId_(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.PROC_DEF_ID_</code>.
	 */
	public java.lang.String getProcDefId_() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.PROC_INST_ID_</code>.
	 */
	public void setProcInstId_(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.PROC_INST_ID_</code>.
	 */
	public java.lang.String getProcInstId_() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.EXECUTION_ID_</code>.
	 */
	public void setExecutionId_(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.EXECUTION_ID_</code>.
	 */
	public java.lang.String getExecutionId_() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.ACT_ID_</code>.
	 */
	public void setActId_(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.ACT_ID_</code>.
	 */
	public java.lang.String getActId_() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.TASK_ID_</code>.
	 */
	public void setTaskId_(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.TASK_ID_</code>.
	 */
	public java.lang.String getTaskId_() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.CALL_PROC_INST_ID_</code>.
	 */
	public void setCallProcInstId_(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.CALL_PROC_INST_ID_</code>.
	 */
	public java.lang.String getCallProcInstId_() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.ACT_NAME_</code>.
	 */
	public void setActName_(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.ACT_NAME_</code>.
	 */
	public java.lang.String getActName_() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.ACT_TYPE_</code>.
	 */
	public void setActType_(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.ACT_TYPE_</code>.
	 */
	public java.lang.String getActType_() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.ASSIGNEE_</code>.
	 */
	public void setAssignee_(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.ASSIGNEE_</code>.
	 */
	public java.lang.String getAssignee_() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.START_TIME_</code>.
	 */
	public void setStartTime_(java.sql.Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.START_TIME_</code>.
	 */
	public java.sql.Timestamp getStartTime_() {
		return (java.sql.Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.END_TIME_</code>.
	 */
	public void setEndTime_(java.sql.Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.END_TIME_</code>.
	 */
	public java.sql.Timestamp getEndTime_() {
		return (java.sql.Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.DURATION_</code>.
	 */
	public void setDuration_(java.lang.Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.DURATION_</code>.
	 */
	public java.lang.Long getDuration_() {
		return (java.lang.Long) getValue(13);
	}

	/**
	 * Setter for <code>process-engine.ACT_HI_ACTINST.ACT_INST_STATE_</code>.
	 */
	public void setActInstState_(java.lang.Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_HI_ACTINST.ACT_INST_STATE_</code>.
	 */
	public java.lang.Integer getActInstState_() {
		return (java.lang.Integer) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long, java.lang.Integer> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.PARENT_ACT_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.PROC_DEF_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.PROC_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.EXECUTION_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.ACT_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.TASK_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.CALL_PROC_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.ACT_NAME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.ACT_TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.ASSIGNEE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field12() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.START_TIME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field13() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.END_TIME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field14() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.DURATION_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field15() {
		return schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST.ACT_INST_STATE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getParentActInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getProcDefId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getProcInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getExecutionId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getActId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getTaskId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getCallProcInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getActName_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getActType_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getAssignee_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value12() {
		return getStartTime_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value13() {
		return getEndTime_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value14() {
		return getDuration_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value15() {
		return getActInstState_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value1(java.lang.String value) {
		setId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value2(java.lang.String value) {
		setParentActInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value3(java.lang.String value) {
		setProcDefId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value4(java.lang.String value) {
		setProcInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value5(java.lang.String value) {
		setExecutionId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value6(java.lang.String value) {
		setActId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value7(java.lang.String value) {
		setTaskId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value8(java.lang.String value) {
		setCallProcInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value9(java.lang.String value) {
		setActName_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value10(java.lang.String value) {
		setActType_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value11(java.lang.String value) {
		setAssignee_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value12(java.sql.Timestamp value) {
		setStartTime_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value13(java.sql.Timestamp value) {
		setEndTime_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value14(java.lang.Long value) {
		setDuration_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord value15(java.lang.Integer value) {
		setActInstState_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActHiActinstRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11, java.sql.Timestamp value12, java.sql.Timestamp value13, java.lang.Long value14, java.lang.Integer value15) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActHiActinstRecord
	 */
	public ActHiActinstRecord() {
		super(schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST);
	}

	/**
	 * Create a detached, initialised ActHiActinstRecord
	 */
	public ActHiActinstRecord(java.lang.String id_, java.lang.String parentActInstId_, java.lang.String procDefId_, java.lang.String procInstId_, java.lang.String executionId_, java.lang.String actId_, java.lang.String taskId_, java.lang.String callProcInstId_, java.lang.String actName_, java.lang.String actType_, java.lang.String assignee_, java.sql.Timestamp startTime_, java.sql.Timestamp endTime_, java.lang.Long duration_, java.lang.Integer actInstState_) {
		super(schema.process_engine.tables.ActHiActinst.ACT_HI_ACTINST);

		setValue(0, id_);
		setValue(1, parentActInstId_);
		setValue(2, procDefId_);
		setValue(3, procInstId_);
		setValue(4, executionId_);
		setValue(5, actId_);
		setValue(6, taskId_);
		setValue(7, callProcInstId_);
		setValue(8, actName_);
		setValue(9, actType_);
		setValue(10, assignee_);
		setValue(11, startTime_);
		setValue(12, endTime_);
		setValue(13, duration_);
		setValue(14, actInstState_);
	}
}
