/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuAuthorizationRecord extends org.jooq.impl.UpdatableRecordImpl<schema.process_engine.tables.records.ActRuAuthorizationRecord> implements org.jooq.Record8<java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 54223843;

	/**
	 * Setter for <code>process-engine.ACT_RU_AUTHORIZATION.ID_</code>.
	 */
	public void setId_(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_AUTHORIZATION.ID_</code>.
	 */
	public java.lang.String getId_() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_AUTHORIZATION.REV_</code>.
	 */
	public void setRev_(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_AUTHORIZATION.REV_</code>.
	 */
	public java.lang.Integer getRev_() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_AUTHORIZATION.TYPE_</code>.
	 */
	public void setType_(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_AUTHORIZATION.TYPE_</code>.
	 */
	public java.lang.Integer getType_() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_AUTHORIZATION.GROUP_ID_</code>.
	 */
	public void setGroupId_(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_AUTHORIZATION.GROUP_ID_</code>.
	 */
	public java.lang.String getGroupId_() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_AUTHORIZATION.USER_ID_</code>.
	 */
	public void setUserId_(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_AUTHORIZATION.USER_ID_</code>.
	 */
	public java.lang.String getUserId_() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_AUTHORIZATION.RESOURCE_TYPE_</code>.
	 */
	public void setResourceType_(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_AUTHORIZATION.RESOURCE_TYPE_</code>.
	 */
	public java.lang.Integer getResourceType_() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_AUTHORIZATION.RESOURCE_ID_</code>.
	 */
	public void setResourceId_(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_AUTHORIZATION.RESOURCE_ID_</code>.
	 */
	public java.lang.String getResourceId_() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_AUTHORIZATION.PERMS_</code>.
	 */
	public void setPerms_(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_AUTHORIZATION.PERMS_</code>.
	 */
	public java.lang.Integer getPerms_() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION.ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION.REV_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION.TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION.GROUP_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION.USER_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION.RESOURCE_TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION.RESOURCE_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION.PERMS_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRev_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getType_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getGroupId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getUserId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getResourceType_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getResourceId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getPerms_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord value1(java.lang.String value) {
		setId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord value2(java.lang.Integer value) {
		setRev_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord value3(java.lang.Integer value) {
		setType_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord value4(java.lang.String value) {
		setGroupId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord value5(java.lang.String value) {
		setUserId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord value6(java.lang.Integer value) {
		setResourceType_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord value7(java.lang.String value) {
		setResourceId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord value8(java.lang.Integer value) {
		setPerms_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuAuthorizationRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6, java.lang.String value7, java.lang.Integer value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActRuAuthorizationRecord
	 */
	public ActRuAuthorizationRecord() {
		super(schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION);
	}

	/**
	 * Create a detached, initialised ActRuAuthorizationRecord
	 */
	public ActRuAuthorizationRecord(java.lang.String id_, java.lang.Integer rev_, java.lang.Integer type_, java.lang.String groupId_, java.lang.String userId_, java.lang.Integer resourceType_, java.lang.String resourceId_, java.lang.Integer perms_) {
		super(schema.process_engine.tables.ActRuAuthorization.ACT_RU_AUTHORIZATION);

		setValue(0, id_);
		setValue(1, rev_);
		setValue(2, type_);
		setValue(3, groupId_);
		setValue(4, userId_);
		setValue(5, resourceType_);
		setValue(6, resourceId_);
		setValue(7, perms_);
	}
}
