/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuVariableRecord extends org.jooq.impl.UpdatableRecordImpl<schema.process_engine.tables.records.ActRuVariableRecord> implements org.jooq.Record16<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Double, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 198359149;

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.ID_</code>.
	 */
	public void setId_(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.ID_</code>.
	 */
	public java.lang.String getId_() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.REV_</code>.
	 */
	public void setRev_(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.REV_</code>.
	 */
	public java.lang.Integer getRev_() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.TYPE_</code>.
	 */
	public void setType_(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.TYPE_</code>.
	 */
	public java.lang.String getType_() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.NAME_</code>.
	 */
	public void setName_(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.NAME_</code>.
	 */
	public java.lang.String getName_() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.EXECUTION_ID_</code>.
	 */
	public void setExecutionId_(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.EXECUTION_ID_</code>.
	 */
	public java.lang.String getExecutionId_() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.PROC_INST_ID_</code>.
	 */
	public void setProcInstId_(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.PROC_INST_ID_</code>.
	 */
	public java.lang.String getProcInstId_() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.CASE_EXECUTION_ID_</code>.
	 */
	public void setCaseExecutionId_(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.CASE_EXECUTION_ID_</code>.
	 */
	public java.lang.String getCaseExecutionId_() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.CASE_INST_ID_</code>.
	 */
	public void setCaseInstId_(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.CASE_INST_ID_</code>.
	 */
	public java.lang.String getCaseInstId_() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.TASK_ID_</code>.
	 */
	public void setTaskId_(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.TASK_ID_</code>.
	 */
	public java.lang.String getTaskId_() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.BYTEARRAY_ID_</code>.
	 */
	public void setBytearrayId_(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.BYTEARRAY_ID_</code>.
	 */
	public java.lang.String getBytearrayId_() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.DOUBLE_</code>.
	 */
	public void setDouble_(java.lang.Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.DOUBLE_</code>.
	 */
	public java.lang.Double getDouble_() {
		return (java.lang.Double) getValue(10);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.LONG_</code>.
	 */
	public void setLong_(java.lang.Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.LONG_</code>.
	 */
	public java.lang.Long getLong_() {
		return (java.lang.Long) getValue(11);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.TEXT_</code>.
	 */
	public void setText_(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.TEXT_</code>.
	 */
	public java.lang.String getText_() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.TEXT2_</code>.
	 */
	public void setText2_(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.TEXT2_</code>.
	 */
	public java.lang.String getText2_() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.VAR_SCOPE_</code>.
	 */
	public void setVarScope_(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.VAR_SCOPE_</code>.
	 */
	public java.lang.String getVarScope_() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_VARIABLE.DATA_FORMAT_ID_</code>.
	 */
	public void setDataFormatId_(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_VARIABLE.DATA_FORMAT_ID_</code>.
	 */
	public java.lang.String getDataFormatId_() {
		return (java.lang.String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Double, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Double, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.REV_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.NAME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.EXECUTION_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.PROC_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.CASE_EXECUTION_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.CASE_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.TASK_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.BYTEARRAY_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field11() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.DOUBLE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field12() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.LONG_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.TEXT_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.TEXT2_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.VAR_SCOPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE.DATA_FORMAT_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRev_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getExecutionId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getProcInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCaseExecutionId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getCaseInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getTaskId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getBytearrayId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value11() {
		return getDouble_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value12() {
		return getLong_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getText_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getText2_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getVarScope_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getDataFormatId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value1(java.lang.String value) {
		setId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value2(java.lang.Integer value) {
		setRev_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value3(java.lang.String value) {
		setType_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value4(java.lang.String value) {
		setName_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value5(java.lang.String value) {
		setExecutionId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value6(java.lang.String value) {
		setProcInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value7(java.lang.String value) {
		setCaseExecutionId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value8(java.lang.String value) {
		setCaseInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value9(java.lang.String value) {
		setTaskId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value10(java.lang.String value) {
		setBytearrayId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value11(java.lang.Double value) {
		setDouble_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value12(java.lang.Long value) {
		setLong_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value13(java.lang.String value) {
		setText_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value14(java.lang.String value) {
		setText2_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value15(java.lang.String value) {
		setVarScope_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord value16(java.lang.String value) {
		setDataFormatId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuVariableRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.Double value11, java.lang.Long value12, java.lang.String value13, java.lang.String value14, java.lang.String value15, java.lang.String value16) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActRuVariableRecord
	 */
	public ActRuVariableRecord() {
		super(schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE);
	}

	/**
	 * Create a detached, initialised ActRuVariableRecord
	 */
	public ActRuVariableRecord(java.lang.String id_, java.lang.Integer rev_, java.lang.String type_, java.lang.String name_, java.lang.String executionId_, java.lang.String procInstId_, java.lang.String caseExecutionId_, java.lang.String caseInstId_, java.lang.String taskId_, java.lang.String bytearrayId_, java.lang.Double double_, java.lang.Long long_, java.lang.String text_, java.lang.String text2_, java.lang.String varScope_, java.lang.String dataFormatId_) {
		super(schema.process_engine.tables.ActRuVariable.ACT_RU_VARIABLE);

		setValue(0, id_);
		setValue(1, rev_);
		setValue(2, type_);
		setValue(3, name_);
		setValue(4, executionId_);
		setValue(5, procInstId_);
		setValue(6, caseExecutionId_);
		setValue(7, caseInstId_);
		setValue(8, taskId_);
		setValue(9, bytearrayId_);
		setValue(10, double_);
		setValue(11, long_);
		setValue(12, text_);
		setValue(13, text2_);
		setValue(14, varScope_);
		setValue(15, dataFormatId_);
	}
}
