/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuTaskRecord extends org.jooq.impl.UpdatableRecordImpl<schema.process_engine.tables.records.ActRuTaskRecord> implements org.jooq.Record20<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = -758945704;

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.ID_</code>.
	 */
	public void setId_(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.ID_</code>.
	 */
	public java.lang.String getId_() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.REV_</code>.
	 */
	public void setRev_(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.REV_</code>.
	 */
	public java.lang.Integer getRev_() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.EXECUTION_ID_</code>.
	 */
	public void setExecutionId_(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.EXECUTION_ID_</code>.
	 */
	public java.lang.String getExecutionId_() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.PROC_INST_ID_</code>.
	 */
	public void setProcInstId_(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.PROC_INST_ID_</code>.
	 */
	public java.lang.String getProcInstId_() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.PROC_DEF_ID_</code>.
	 */
	public void setProcDefId_(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.PROC_DEF_ID_</code>.
	 */
	public java.lang.String getProcDefId_() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.CASE_EXECUTION_ID_</code>.
	 */
	public void setCaseExecutionId_(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.CASE_EXECUTION_ID_</code>.
	 */
	public java.lang.String getCaseExecutionId_() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.CASE_INST_ID_</code>.
	 */
	public void setCaseInstId_(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.CASE_INST_ID_</code>.
	 */
	public java.lang.String getCaseInstId_() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.CASE_DEF_ID_</code>.
	 */
	public void setCaseDefId_(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.CASE_DEF_ID_</code>.
	 */
	public java.lang.String getCaseDefId_() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.NAME_</code>.
	 */
	public void setName_(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.NAME_</code>.
	 */
	public java.lang.String getName_() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.PARENT_TASK_ID_</code>.
	 */
	public void setParentTaskId_(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.PARENT_TASK_ID_</code>.
	 */
	public java.lang.String getParentTaskId_() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.DESCRIPTION_</code>.
	 */
	public void setDescription_(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.DESCRIPTION_</code>.
	 */
	public java.lang.String getDescription_() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.TASK_DEF_KEY_</code>.
	 */
	public void setTaskDefKey_(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.TASK_DEF_KEY_</code>.
	 */
	public java.lang.String getTaskDefKey_() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.OWNER_</code>.
	 */
	public void setOwner_(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.OWNER_</code>.
	 */
	public java.lang.String getOwner_() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.ASSIGNEE_</code>.
	 */
	public void setAssignee_(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.ASSIGNEE_</code>.
	 */
	public java.lang.String getAssignee_() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.DELEGATION_</code>.
	 */
	public void setDelegation_(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.DELEGATION_</code>.
	 */
	public java.lang.String getDelegation_() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.PRIORITY_</code>.
	 */
	public void setPriority_(java.lang.Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.PRIORITY_</code>.
	 */
	public java.lang.Integer getPriority_() {
		return (java.lang.Integer) getValue(15);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.CREATE_TIME_</code>.
	 */
	public void setCreateTime_(java.sql.Timestamp value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.CREATE_TIME_</code>.
	 */
	public java.sql.Timestamp getCreateTime_() {
		return (java.sql.Timestamp) getValue(16);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.DUE_DATE_</code>.
	 */
	public void setDueDate_(java.sql.Timestamp value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.DUE_DATE_</code>.
	 */
	public java.sql.Timestamp getDueDate_() {
		return (java.sql.Timestamp) getValue(17);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.FOLLOW_UP_DATE_</code>.
	 */
	public void setFollowUpDate_(java.sql.Timestamp value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.FOLLOW_UP_DATE_</code>.
	 */
	public java.sql.Timestamp getFollowUpDate_() {
		return (java.sql.Timestamp) getValue(18);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_TASK.SUSPENSION_STATE_</code>.
	 */
	public void setSuspensionState_(java.lang.Integer value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_TASK.SUSPENSION_STATE_</code>.
	 */
	public java.lang.Integer getSuspensionState_() {
		return (java.lang.Integer) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.REV_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.EXECUTION_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.PROC_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.PROC_DEF_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.CASE_EXECUTION_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.CASE_INST_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.CASE_DEF_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.NAME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.PARENT_TASK_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.DESCRIPTION_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.TASK_DEF_KEY_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.OWNER_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.ASSIGNEE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.DELEGATION_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field16() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.PRIORITY_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field17() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.CREATE_TIME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field18() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.DUE_DATE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field19() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.FOLLOW_UP_DATE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field20() {
		return schema.process_engine.tables.ActRuTask.ACT_RU_TASK.SUSPENSION_STATE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRev_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getExecutionId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getProcInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getProcDefId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCaseExecutionId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCaseInstId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getCaseDefId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getName_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getParentTaskId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getDescription_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getTaskDefKey_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getOwner_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getAssignee_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getDelegation_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value16() {
		return getPriority_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value17() {
		return getCreateTime_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value18() {
		return getDueDate_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value19() {
		return getFollowUpDate_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value20() {
		return getSuspensionState_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value1(java.lang.String value) {
		setId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value2(java.lang.Integer value) {
		setRev_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value3(java.lang.String value) {
		setExecutionId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value4(java.lang.String value) {
		setProcInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value5(java.lang.String value) {
		setProcDefId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value6(java.lang.String value) {
		setCaseExecutionId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value7(java.lang.String value) {
		setCaseInstId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value8(java.lang.String value) {
		setCaseDefId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value9(java.lang.String value) {
		setName_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value10(java.lang.String value) {
		setParentTaskId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value11(java.lang.String value) {
		setDescription_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value12(java.lang.String value) {
		setTaskDefKey_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value13(java.lang.String value) {
		setOwner_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value14(java.lang.String value) {
		setAssignee_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value15(java.lang.String value) {
		setDelegation_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value16(java.lang.Integer value) {
		setPriority_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value17(java.sql.Timestamp value) {
		setCreateTime_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value18(java.sql.Timestamp value) {
		setDueDate_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value19(java.sql.Timestamp value) {
		setFollowUpDate_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord value20(java.lang.Integer value) {
		setSuspensionState_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuTaskRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11, java.lang.String value12, java.lang.String value13, java.lang.String value14, java.lang.String value15, java.lang.Integer value16, java.sql.Timestamp value17, java.sql.Timestamp value18, java.sql.Timestamp value19, java.lang.Integer value20) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActRuTaskRecord
	 */
	public ActRuTaskRecord() {
		super(schema.process_engine.tables.ActRuTask.ACT_RU_TASK);
	}

	/**
	 * Create a detached, initialised ActRuTaskRecord
	 */
	public ActRuTaskRecord(java.lang.String id_, java.lang.Integer rev_, java.lang.String executionId_, java.lang.String procInstId_, java.lang.String procDefId_, java.lang.String caseExecutionId_, java.lang.String caseInstId_, java.lang.String caseDefId_, java.lang.String name_, java.lang.String parentTaskId_, java.lang.String description_, java.lang.String taskDefKey_, java.lang.String owner_, java.lang.String assignee_, java.lang.String delegation_, java.lang.Integer priority_, java.sql.Timestamp createTime_, java.sql.Timestamp dueDate_, java.sql.Timestamp followUpDate_, java.lang.Integer suspensionState_) {
		super(schema.process_engine.tables.ActRuTask.ACT_RU_TASK);

		setValue(0, id_);
		setValue(1, rev_);
		setValue(2, executionId_);
		setValue(3, procInstId_);
		setValue(4, procDefId_);
		setValue(5, caseExecutionId_);
		setValue(6, caseInstId_);
		setValue(7, caseDefId_);
		setValue(8, name_);
		setValue(9, parentTaskId_);
		setValue(10, description_);
		setValue(11, taskDefKey_);
		setValue(12, owner_);
		setValue(13, assignee_);
		setValue(14, delegation_);
		setValue(15, priority_);
		setValue(16, createTime_);
		setValue(17, dueDate_);
		setValue(18, followUpDate_);
		setValue(19, suspensionState_);
	}
}
