/**
 * This class is generated by jOOQ
 */
package schema.process_engine.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuJobRecord extends org.jooq.impl.UpdatableRecordImpl<schema.process_engine.tables.records.ActRuJobRecord> implements org.jooq.Record20<java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1660439987;

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.ID_</code>.
	 */
	public void setId_(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.ID_</code>.
	 */
	public java.lang.String getId_() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.REV_</code>.
	 */
	public void setRev_(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.REV_</code>.
	 */
	public java.lang.Integer getRev_() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.TYPE_</code>.
	 */
	public void setType_(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.TYPE_</code>.
	 */
	public java.lang.String getType_() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.LOCK_EXP_TIME_</code>.
	 */
	public void setLockExpTime_(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.LOCK_EXP_TIME_</code>.
	 */
	public java.sql.Timestamp getLockExpTime_() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.LOCK_OWNER_</code>.
	 */
	public void setLockOwner_(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.LOCK_OWNER_</code>.
	 */
	public java.lang.String getLockOwner_() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.EXCLUSIVE_</code>.
	 */
	public void setExclusive_(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.EXCLUSIVE_</code>.
	 */
	public java.lang.Byte getExclusive_() {
		return (java.lang.Byte) getValue(5);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.EXECUTION_ID_</code>.
	 */
	public void setExecutionId_(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.EXECUTION_ID_</code>.
	 */
	public java.lang.String getExecutionId_() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.PROCESS_INSTANCE_ID_</code>.
	 */
	public void setProcessInstanceId_(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.PROCESS_INSTANCE_ID_</code>.
	 */
	public java.lang.String getProcessInstanceId_() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.PROCESS_DEF_ID_</code>.
	 */
	public void setProcessDefId_(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.PROCESS_DEF_ID_</code>.
	 */
	public java.lang.String getProcessDefId_() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.PROCESS_DEF_KEY_</code>.
	 */
	public void setProcessDefKey_(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.PROCESS_DEF_KEY_</code>.
	 */
	public java.lang.String getProcessDefKey_() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.RETRIES_</code>.
	 */
	public void setRetries_(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.RETRIES_</code>.
	 */
	public java.lang.Integer getRetries_() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.EXCEPTION_STACK_ID_</code>.
	 */
	public void setExceptionStackId_(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.EXCEPTION_STACK_ID_</code>.
	 */
	public java.lang.String getExceptionStackId_() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.EXCEPTION_MSG_</code>.
	 */
	public void setExceptionMsg_(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.EXCEPTION_MSG_</code>.
	 */
	public java.lang.String getExceptionMsg_() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.DUEDATE_</code>.
	 */
	public void setDuedate_(java.sql.Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.DUEDATE_</code>.
	 */
	public java.sql.Timestamp getDuedate_() {
		return (java.sql.Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.REPEAT_</code>.
	 */
	public void setRepeat_(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.REPEAT_</code>.
	 */
	public java.lang.String getRepeat_() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.HANDLER_TYPE_</code>.
	 */
	public void setHandlerType_(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.HANDLER_TYPE_</code>.
	 */
	public java.lang.String getHandlerType_() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.HANDLER_CFG_</code>.
	 */
	public void setHandlerCfg_(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.HANDLER_CFG_</code>.
	 */
	public java.lang.String getHandlerCfg_() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.DEPLOYMENT_ID_</code>.
	 */
	public void setDeploymentId_(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.DEPLOYMENT_ID_</code>.
	 */
	public java.lang.String getDeploymentId_() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.SUSPENSION_STATE_</code>.
	 */
	public void setSuspensionState_(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.SUSPENSION_STATE_</code>.
	 */
	public java.lang.Integer getSuspensionState_() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>process-engine.ACT_RU_JOB.JOB_DEF_ID_</code>.
	 */
	public void setJobDefId_(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>process-engine.ACT_RU_JOB.JOB_DEF_ID_</code>.
	 */
	public java.lang.String getJobDefId_() {
		return (java.lang.String) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.REV_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.LOCK_EXP_TIME_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.LOCK_OWNER_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field6() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.EXCLUSIVE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.EXECUTION_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.PROCESS_INSTANCE_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.PROCESS_DEF_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.PROCESS_DEF_KEY_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.RETRIES_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.EXCEPTION_STACK_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.EXCEPTION_MSG_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field14() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.DUEDATE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.REPEAT_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.HANDLER_TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field17() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.HANDLER_CFG_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field18() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.DEPLOYMENT_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field19() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.SUSPENSION_STATE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field20() {
		return schema.process_engine.tables.ActRuJob.ACT_RU_JOB.JOB_DEF_ID_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRev_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getLockExpTime_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getLockOwner_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value6() {
		return getExclusive_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getExecutionId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getProcessInstanceId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getProcessDefId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getProcessDefKey_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getRetries_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getExceptionStackId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getExceptionMsg_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value14() {
		return getDuedate_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getRepeat_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getHandlerType_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value17() {
		return getHandlerCfg_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value18() {
		return getDeploymentId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value19() {
		return getSuspensionState_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value20() {
		return getJobDefId_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value1(java.lang.String value) {
		setId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value2(java.lang.Integer value) {
		setRev_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value3(java.lang.String value) {
		setType_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value4(java.sql.Timestamp value) {
		setLockExpTime_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value5(java.lang.String value) {
		setLockOwner_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value6(java.lang.Byte value) {
		setExclusive_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value7(java.lang.String value) {
		setExecutionId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value8(java.lang.String value) {
		setProcessInstanceId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value9(java.lang.String value) {
		setProcessDefId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value10(java.lang.String value) {
		setProcessDefKey_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value11(java.lang.Integer value) {
		setRetries_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value12(java.lang.String value) {
		setExceptionStackId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value13(java.lang.String value) {
		setExceptionMsg_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value14(java.sql.Timestamp value) {
		setDuedate_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value15(java.lang.String value) {
		setRepeat_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value16(java.lang.String value) {
		setHandlerType_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value17(java.lang.String value) {
		setHandlerCfg_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value18(java.lang.String value) {
		setDeploymentId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value19(java.lang.Integer value) {
		setSuspensionState_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord value20(java.lang.String value) {
		setJobDefId_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActRuJobRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.String value5, java.lang.Byte value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.Integer value11, java.lang.String value12, java.lang.String value13, java.sql.Timestamp value14, java.lang.String value15, java.lang.String value16, java.lang.String value17, java.lang.String value18, java.lang.Integer value19, java.lang.String value20) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActRuJobRecord
	 */
	public ActRuJobRecord() {
		super(schema.process_engine.tables.ActRuJob.ACT_RU_JOB);
	}

	/**
	 * Create a detached, initialised ActRuJobRecord
	 */
	public ActRuJobRecord(java.lang.String id_, java.lang.Integer rev_, java.lang.String type_, java.sql.Timestamp lockExpTime_, java.lang.String lockOwner_, java.lang.Byte exclusive_, java.lang.String executionId_, java.lang.String processInstanceId_, java.lang.String processDefId_, java.lang.String processDefKey_, java.lang.Integer retries_, java.lang.String exceptionStackId_, java.lang.String exceptionMsg_, java.sql.Timestamp duedate_, java.lang.String repeat_, java.lang.String handlerType_, java.lang.String handlerCfg_, java.lang.String deploymentId_, java.lang.Integer suspensionState_, java.lang.String jobDefId_) {
		super(schema.process_engine.tables.ActRuJob.ACT_RU_JOB);

		setValue(0, id_);
		setValue(1, rev_);
		setValue(2, type_);
		setValue(3, lockExpTime_);
		setValue(4, lockOwner_);
		setValue(5, exclusive_);
		setValue(6, executionId_);
		setValue(7, processInstanceId_);
		setValue(8, processDefId_);
		setValue(9, processDefKey_);
		setValue(10, retries_);
		setValue(11, exceptionStackId_);
		setValue(12, exceptionMsg_);
		setValue(13, duedate_);
		setValue(14, repeat_);
		setValue(15, handlerType_);
		setValue(16, handlerCfg_);
		setValue(17, deploymentId_);
		setValue(18, suspensionState_);
		setValue(19, jobDefId_);
	}
}
