/**
 * This class is generated by jOOQ
 */
package cleandb.mysql;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mysql extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1647177482;

	/**
	 * The reference instance of <code>mysql</code>
	 */
	public static final Mysql MYSQL = new Mysql();

	/**
	 * No further instances allowed
	 */
	private Mysql() {
		super("mysql");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			cleandb.mysql.tables.ColumnsPriv.COLUMNS_PRIV,
			cleandb.mysql.tables.Db.DB,
			cleandb.mysql.tables.Event.EVENT,
			cleandb.mysql.tables.Func.FUNC,
			cleandb.mysql.tables.GeneralLog.GENERAL_LOG,
			cleandb.mysql.tables.HelpCategory.HELP_CATEGORY,
			cleandb.mysql.tables.HelpKeyword.HELP_KEYWORD,
			cleandb.mysql.tables.HelpRelation.HELP_RELATION,
			cleandb.mysql.tables.HelpTopic.HELP_TOPIC,
			cleandb.mysql.tables.Host.HOST,
			cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX,
			cleandb.mysql.tables.Plugin.PLUGIN,
			cleandb.mysql.tables.Proc.PROC,
			cleandb.mysql.tables.ProcsPriv.PROCS_PRIV,
			cleandb.mysql.tables.ProxiesPriv.PROXIES_PRIV,
			cleandb.mysql.tables.Servers.SERVERS,
			cleandb.mysql.tables.SlowLog.SLOW_LOG,
			cleandb.mysql.tables.TablesPriv.TABLES_PRIV,
			cleandb.mysql.tables.TimeZone.TIME_ZONE,
			cleandb.mysql.tables.TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND,
			cleandb.mysql.tables.TimeZoneName.TIME_ZONE_NAME,
			cleandb.mysql.tables.TimeZoneTransition.TIME_ZONE_TRANSITION,
			cleandb.mysql.tables.TimeZoneTransitionType.TIME_ZONE_TRANSITION_TYPE,
			cleandb.mysql.tables.User.USER);
	}
}
