/**
 * This class is generated by jOOQ
 */
package schema.mysql.tables.records;

/**
 * Host privileges;  Merged with database privileges
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostRecord extends org.jooq.impl.UpdatableRecordImpl<schema.mysql.tables.records.HostRecord> implements org.jooq.Record20<java.lang.String, java.lang.String, schema.mysql.enums.HostSelectPriv, schema.mysql.enums.HostInsertPriv, schema.mysql.enums.HostUpdatePriv, schema.mysql.enums.HostDeletePriv, schema.mysql.enums.HostCreatePriv, schema.mysql.enums.HostDropPriv, schema.mysql.enums.HostGrantPriv, schema.mysql.enums.HostReferencesPriv, schema.mysql.enums.HostIndexPriv, schema.mysql.enums.HostAlterPriv, schema.mysql.enums.HostCreateTmpTablePriv, schema.mysql.enums.HostLockTablesPriv, schema.mysql.enums.HostCreateViewPriv, schema.mysql.enums.HostShowViewPriv, schema.mysql.enums.HostCreateRoutinePriv, schema.mysql.enums.HostAlterRoutinePriv, schema.mysql.enums.HostExecutePriv, schema.mysql.enums.HostTriggerPriv> {

	private static final long serialVersionUID = -1594684613;

	/**
	 * Setter for <code>mysql.host.Host</code>.
	 */
	public void setHost(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mysql.host.Host</code>.
	 */
	public java.lang.String getHost() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>mysql.host.Db</code>.
	 */
	public void setDb(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mysql.host.Db</code>.
	 */
	public java.lang.String getDb() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>mysql.host.Select_priv</code>.
	 */
	public void setSelectPriv(schema.mysql.enums.HostSelectPriv value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mysql.host.Select_priv</code>.
	 */
	public schema.mysql.enums.HostSelectPriv getSelectPriv() {
		return (schema.mysql.enums.HostSelectPriv) getValue(2);
	}

	/**
	 * Setter for <code>mysql.host.Insert_priv</code>.
	 */
	public void setInsertPriv(schema.mysql.enums.HostInsertPriv value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mysql.host.Insert_priv</code>.
	 */
	public schema.mysql.enums.HostInsertPriv getInsertPriv() {
		return (schema.mysql.enums.HostInsertPriv) getValue(3);
	}

	/**
	 * Setter for <code>mysql.host.Update_priv</code>.
	 */
	public void setUpdatePriv(schema.mysql.enums.HostUpdatePriv value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mysql.host.Update_priv</code>.
	 */
	public schema.mysql.enums.HostUpdatePriv getUpdatePriv() {
		return (schema.mysql.enums.HostUpdatePriv) getValue(4);
	}

	/**
	 * Setter for <code>mysql.host.Delete_priv</code>.
	 */
	public void setDeletePriv(schema.mysql.enums.HostDeletePriv value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mysql.host.Delete_priv</code>.
	 */
	public schema.mysql.enums.HostDeletePriv getDeletePriv() {
		return (schema.mysql.enums.HostDeletePriv) getValue(5);
	}

	/**
	 * Setter for <code>mysql.host.Create_priv</code>.
	 */
	public void setCreatePriv(schema.mysql.enums.HostCreatePriv value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mysql.host.Create_priv</code>.
	 */
	public schema.mysql.enums.HostCreatePriv getCreatePriv() {
		return (schema.mysql.enums.HostCreatePriv) getValue(6);
	}

	/**
	 * Setter for <code>mysql.host.Drop_priv</code>.
	 */
	public void setDropPriv(schema.mysql.enums.HostDropPriv value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mysql.host.Drop_priv</code>.
	 */
	public schema.mysql.enums.HostDropPriv getDropPriv() {
		return (schema.mysql.enums.HostDropPriv) getValue(7);
	}

	/**
	 * Setter for <code>mysql.host.Grant_priv</code>.
	 */
	public void setGrantPriv(schema.mysql.enums.HostGrantPriv value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mysql.host.Grant_priv</code>.
	 */
	public schema.mysql.enums.HostGrantPriv getGrantPriv() {
		return (schema.mysql.enums.HostGrantPriv) getValue(8);
	}

	/**
	 * Setter for <code>mysql.host.References_priv</code>.
	 */
	public void setReferencesPriv(schema.mysql.enums.HostReferencesPriv value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mysql.host.References_priv</code>.
	 */
	public schema.mysql.enums.HostReferencesPriv getReferencesPriv() {
		return (schema.mysql.enums.HostReferencesPriv) getValue(9);
	}

	/**
	 * Setter for <code>mysql.host.Index_priv</code>.
	 */
	public void setIndexPriv(schema.mysql.enums.HostIndexPriv value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>mysql.host.Index_priv</code>.
	 */
	public schema.mysql.enums.HostIndexPriv getIndexPriv() {
		return (schema.mysql.enums.HostIndexPriv) getValue(10);
	}

	/**
	 * Setter for <code>mysql.host.Alter_priv</code>.
	 */
	public void setAlterPriv(schema.mysql.enums.HostAlterPriv value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>mysql.host.Alter_priv</code>.
	 */
	public schema.mysql.enums.HostAlterPriv getAlterPriv() {
		return (schema.mysql.enums.HostAlterPriv) getValue(11);
	}

	/**
	 * Setter for <code>mysql.host.Create_tmp_table_priv</code>.
	 */
	public void setCreateTmpTablePriv(schema.mysql.enums.HostCreateTmpTablePriv value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>mysql.host.Create_tmp_table_priv</code>.
	 */
	public schema.mysql.enums.HostCreateTmpTablePriv getCreateTmpTablePriv() {
		return (schema.mysql.enums.HostCreateTmpTablePriv) getValue(12);
	}

	/**
	 * Setter for <code>mysql.host.Lock_tables_priv</code>.
	 */
	public void setLockTablesPriv(schema.mysql.enums.HostLockTablesPriv value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>mysql.host.Lock_tables_priv</code>.
	 */
	public schema.mysql.enums.HostLockTablesPriv getLockTablesPriv() {
		return (schema.mysql.enums.HostLockTablesPriv) getValue(13);
	}

	/**
	 * Setter for <code>mysql.host.Create_view_priv</code>.
	 */
	public void setCreateViewPriv(schema.mysql.enums.HostCreateViewPriv value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>mysql.host.Create_view_priv</code>.
	 */
	public schema.mysql.enums.HostCreateViewPriv getCreateViewPriv() {
		return (schema.mysql.enums.HostCreateViewPriv) getValue(14);
	}

	/**
	 * Setter for <code>mysql.host.Show_view_priv</code>.
	 */
	public void setShowViewPriv(schema.mysql.enums.HostShowViewPriv value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>mysql.host.Show_view_priv</code>.
	 */
	public schema.mysql.enums.HostShowViewPriv getShowViewPriv() {
		return (schema.mysql.enums.HostShowViewPriv) getValue(15);
	}

	/**
	 * Setter for <code>mysql.host.Create_routine_priv</code>.
	 */
	public void setCreateRoutinePriv(schema.mysql.enums.HostCreateRoutinePriv value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>mysql.host.Create_routine_priv</code>.
	 */
	public schema.mysql.enums.HostCreateRoutinePriv getCreateRoutinePriv() {
		return (schema.mysql.enums.HostCreateRoutinePriv) getValue(16);
	}

	/**
	 * Setter for <code>mysql.host.Alter_routine_priv</code>.
	 */
	public void setAlterRoutinePriv(schema.mysql.enums.HostAlterRoutinePriv value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>mysql.host.Alter_routine_priv</code>.
	 */
	public schema.mysql.enums.HostAlterRoutinePriv getAlterRoutinePriv() {
		return (schema.mysql.enums.HostAlterRoutinePriv) getValue(17);
	}

	/**
	 * Setter for <code>mysql.host.Execute_priv</code>.
	 */
	public void setExecutePriv(schema.mysql.enums.HostExecutePriv value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>mysql.host.Execute_priv</code>.
	 */
	public schema.mysql.enums.HostExecutePriv getExecutePriv() {
		return (schema.mysql.enums.HostExecutePriv) getValue(18);
	}

	/**
	 * Setter for <code>mysql.host.Trigger_priv</code>.
	 */
	public void setTriggerPriv(schema.mysql.enums.HostTriggerPriv value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>mysql.host.Trigger_priv</code>.
	 */
	public schema.mysql.enums.HostTriggerPriv getTriggerPriv() {
		return (schema.mysql.enums.HostTriggerPriv) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.String, java.lang.String, schema.mysql.enums.HostSelectPriv, schema.mysql.enums.HostInsertPriv, schema.mysql.enums.HostUpdatePriv, schema.mysql.enums.HostDeletePriv, schema.mysql.enums.HostCreatePriv, schema.mysql.enums.HostDropPriv, schema.mysql.enums.HostGrantPriv, schema.mysql.enums.HostReferencesPriv, schema.mysql.enums.HostIndexPriv, schema.mysql.enums.HostAlterPriv, schema.mysql.enums.HostCreateTmpTablePriv, schema.mysql.enums.HostLockTablesPriv, schema.mysql.enums.HostCreateViewPriv, schema.mysql.enums.HostShowViewPriv, schema.mysql.enums.HostCreateRoutinePriv, schema.mysql.enums.HostAlterRoutinePriv, schema.mysql.enums.HostExecutePriv, schema.mysql.enums.HostTriggerPriv> fieldsRow() {
		return (org.jooq.Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.String, java.lang.String, schema.mysql.enums.HostSelectPriv, schema.mysql.enums.HostInsertPriv, schema.mysql.enums.HostUpdatePriv, schema.mysql.enums.HostDeletePriv, schema.mysql.enums.HostCreatePriv, schema.mysql.enums.HostDropPriv, schema.mysql.enums.HostGrantPriv, schema.mysql.enums.HostReferencesPriv, schema.mysql.enums.HostIndexPriv, schema.mysql.enums.HostAlterPriv, schema.mysql.enums.HostCreateTmpTablePriv, schema.mysql.enums.HostLockTablesPriv, schema.mysql.enums.HostCreateViewPriv, schema.mysql.enums.HostShowViewPriv, schema.mysql.enums.HostCreateRoutinePriv, schema.mysql.enums.HostAlterRoutinePriv, schema.mysql.enums.HostExecutePriv, schema.mysql.enums.HostTriggerPriv> valuesRow() {
		return (org.jooq.Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return schema.mysql.tables.Host.HOST.HOST_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return schema.mysql.tables.Host.HOST.DB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostSelectPriv> field3() {
		return schema.mysql.tables.Host.HOST.SELECT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostInsertPriv> field4() {
		return schema.mysql.tables.Host.HOST.INSERT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostUpdatePriv> field5() {
		return schema.mysql.tables.Host.HOST.UPDATE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostDeletePriv> field6() {
		return schema.mysql.tables.Host.HOST.DELETE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostCreatePriv> field7() {
		return schema.mysql.tables.Host.HOST.CREATE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostDropPriv> field8() {
		return schema.mysql.tables.Host.HOST.DROP_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostGrantPriv> field9() {
		return schema.mysql.tables.Host.HOST.GRANT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostReferencesPriv> field10() {
		return schema.mysql.tables.Host.HOST.REFERENCES_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostIndexPriv> field11() {
		return schema.mysql.tables.Host.HOST.INDEX_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostAlterPriv> field12() {
		return schema.mysql.tables.Host.HOST.ALTER_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostCreateTmpTablePriv> field13() {
		return schema.mysql.tables.Host.HOST.CREATE_TMP_TABLE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostLockTablesPriv> field14() {
		return schema.mysql.tables.Host.HOST.LOCK_TABLES_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostCreateViewPriv> field15() {
		return schema.mysql.tables.Host.HOST.CREATE_VIEW_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostShowViewPriv> field16() {
		return schema.mysql.tables.Host.HOST.SHOW_VIEW_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostCreateRoutinePriv> field17() {
		return schema.mysql.tables.Host.HOST.CREATE_ROUTINE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostAlterRoutinePriv> field18() {
		return schema.mysql.tables.Host.HOST.ALTER_ROUTINE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostExecutePriv> field19() {
		return schema.mysql.tables.Host.HOST.EXECUTE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<schema.mysql.enums.HostTriggerPriv> field20() {
		return schema.mysql.tables.Host.HOST.TRIGGER_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getHost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDb();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostSelectPriv value3() {
		return getSelectPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostInsertPriv value4() {
		return getInsertPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostUpdatePriv value5() {
		return getUpdatePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostDeletePriv value6() {
		return getDeletePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostCreatePriv value7() {
		return getCreatePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostDropPriv value8() {
		return getDropPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostGrantPriv value9() {
		return getGrantPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostReferencesPriv value10() {
		return getReferencesPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostIndexPriv value11() {
		return getIndexPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostAlterPriv value12() {
		return getAlterPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostCreateTmpTablePriv value13() {
		return getCreateTmpTablePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostLockTablesPriv value14() {
		return getLockTablesPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostCreateViewPriv value15() {
		return getCreateViewPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostShowViewPriv value16() {
		return getShowViewPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostCreateRoutinePriv value17() {
		return getCreateRoutinePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostAlterRoutinePriv value18() {
		return getAlterRoutinePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostExecutePriv value19() {
		return getExecutePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.mysql.enums.HostTriggerPriv value20() {
		return getTriggerPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value1(java.lang.String value) {
		setHost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value2(java.lang.String value) {
		setDb(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value3(schema.mysql.enums.HostSelectPriv value) {
		setSelectPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value4(schema.mysql.enums.HostInsertPriv value) {
		setInsertPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value5(schema.mysql.enums.HostUpdatePriv value) {
		setUpdatePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value6(schema.mysql.enums.HostDeletePriv value) {
		setDeletePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value7(schema.mysql.enums.HostCreatePriv value) {
		setCreatePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value8(schema.mysql.enums.HostDropPriv value) {
		setDropPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value9(schema.mysql.enums.HostGrantPriv value) {
		setGrantPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value10(schema.mysql.enums.HostReferencesPriv value) {
		setReferencesPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value11(schema.mysql.enums.HostIndexPriv value) {
		setIndexPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value12(schema.mysql.enums.HostAlterPriv value) {
		setAlterPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value13(schema.mysql.enums.HostCreateTmpTablePriv value) {
		setCreateTmpTablePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value14(schema.mysql.enums.HostLockTablesPriv value) {
		setLockTablesPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value15(schema.mysql.enums.HostCreateViewPriv value) {
		setCreateViewPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value16(schema.mysql.enums.HostShowViewPriv value) {
		setShowViewPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value17(schema.mysql.enums.HostCreateRoutinePriv value) {
		setCreateRoutinePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value18(schema.mysql.enums.HostAlterRoutinePriv value) {
		setAlterRoutinePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value19(schema.mysql.enums.HostExecutePriv value) {
		setExecutePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value20(schema.mysql.enums.HostTriggerPriv value) {
		setTriggerPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord values(java.lang.String value1, java.lang.String value2, schema.mysql.enums.HostSelectPriv value3, schema.mysql.enums.HostInsertPriv value4, schema.mysql.enums.HostUpdatePriv value5, schema.mysql.enums.HostDeletePriv value6, schema.mysql.enums.HostCreatePriv value7, schema.mysql.enums.HostDropPriv value8, schema.mysql.enums.HostGrantPriv value9, schema.mysql.enums.HostReferencesPriv value10, schema.mysql.enums.HostIndexPriv value11, schema.mysql.enums.HostAlterPriv value12, schema.mysql.enums.HostCreateTmpTablePriv value13, schema.mysql.enums.HostLockTablesPriv value14, schema.mysql.enums.HostCreateViewPriv value15, schema.mysql.enums.HostShowViewPriv value16, schema.mysql.enums.HostCreateRoutinePriv value17, schema.mysql.enums.HostAlterRoutinePriv value18, schema.mysql.enums.HostExecutePriv value19, schema.mysql.enums.HostTriggerPriv value20) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HostRecord
	 */
	public HostRecord() {
		super(schema.mysql.tables.Host.HOST);
	}

	/**
	 * Create a detached, initialised HostRecord
	 */
	public HostRecord(java.lang.String host, java.lang.String db, schema.mysql.enums.HostSelectPriv selectPriv, schema.mysql.enums.HostInsertPriv insertPriv, schema.mysql.enums.HostUpdatePriv updatePriv, schema.mysql.enums.HostDeletePriv deletePriv, schema.mysql.enums.HostCreatePriv createPriv, schema.mysql.enums.HostDropPriv dropPriv, schema.mysql.enums.HostGrantPriv grantPriv, schema.mysql.enums.HostReferencesPriv referencesPriv, schema.mysql.enums.HostIndexPriv indexPriv, schema.mysql.enums.HostAlterPriv alterPriv, schema.mysql.enums.HostCreateTmpTablePriv createTmpTablePriv, schema.mysql.enums.HostLockTablesPriv lockTablesPriv, schema.mysql.enums.HostCreateViewPriv createViewPriv, schema.mysql.enums.HostShowViewPriv showViewPriv, schema.mysql.enums.HostCreateRoutinePriv createRoutinePriv, schema.mysql.enums.HostAlterRoutinePriv alterRoutinePriv, schema.mysql.enums.HostExecutePriv executePriv, schema.mysql.enums.HostTriggerPriv triggerPriv) {
		super(schema.mysql.tables.Host.HOST);

		setValue(0, host);
		setValue(1, db);
		setValue(2, selectPriv);
		setValue(3, insertPriv);
		setValue(4, updatePriv);
		setValue(5, deletePriv);
		setValue(6, createPriv);
		setValue(7, dropPriv);
		setValue(8, grantPriv);
		setValue(9, referencesPriv);
		setValue(10, indexPriv);
		setValue(11, alterPriv);
		setValue(12, createTmpTablePriv);
		setValue(13, lockTablesPriv);
		setValue(14, createViewPriv);
		setValue(15, showViewPriv);
		setValue(16, createRoutinePriv);
		setValue(17, alterRoutinePriv);
		setValue(18, executePriv);
		setValue(19, triggerPriv);
	}
}
