/**
 * This class is generated by jOOQ
 */
package schema.performance_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileSummaryByInstance extends org.jooq.impl.TableImpl<schema.performance_schema.tables.records.FileSummaryByInstanceRecord> {

	private static final long serialVersionUID = -1101776238;

	/**
	 * The reference instance of <code>performance_schema.file_summary_by_instance</code>
	 */
	public static final schema.performance_schema.tables.FileSummaryByInstance FILE_SUMMARY_BY_INSTANCE = new schema.performance_schema.tables.FileSummaryByInstance();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.performance_schema.tables.records.FileSummaryByInstanceRecord> getRecordType() {
		return schema.performance_schema.tables.records.FileSummaryByInstanceRecord.class;
	}

	/**
	 * The column <code>performance_schema.file_summary_by_instance.FILE_NAME</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.FileSummaryByInstanceRecord, java.lang.String> FILE_NAME = createField("FILE_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(512).nullable(false), this, "");

	/**
	 * The column <code>performance_schema.file_summary_by_instance.EVENT_NAME</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.FileSummaryByInstanceRecord, java.lang.String> EVENT_NAME = createField("EVENT_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>performance_schema.file_summary_by_instance.COUNT_READ</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.FileSummaryByInstanceRecord, org.jooq.types.ULong> COUNT_READ = createField("COUNT_READ", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>performance_schema.file_summary_by_instance.COUNT_WRITE</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.FileSummaryByInstanceRecord, org.jooq.types.ULong> COUNT_WRITE = createField("COUNT_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>performance_schema.file_summary_by_instance.SUM_NUMBER_OF_BYTES_READ</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.FileSummaryByInstanceRecord, org.jooq.types.ULong> SUM_NUMBER_OF_BYTES_READ = createField("SUM_NUMBER_OF_BYTES_READ", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>performance_schema.file_summary_by_instance.SUM_NUMBER_OF_BYTES_WRITE</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.FileSummaryByInstanceRecord, org.jooq.types.ULong> SUM_NUMBER_OF_BYTES_WRITE = createField("SUM_NUMBER_OF_BYTES_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

	/**
	 * Create a <code>performance_schema.file_summary_by_instance</code> table reference
	 */
	public FileSummaryByInstance() {
		this("file_summary_by_instance", null);
	}

	/**
	 * Create an aliased <code>performance_schema.file_summary_by_instance</code> table reference
	 */
	public FileSummaryByInstance(java.lang.String alias) {
		this(alias, schema.performance_schema.tables.FileSummaryByInstance.FILE_SUMMARY_BY_INSTANCE);
	}

	private FileSummaryByInstance(java.lang.String alias, org.jooq.Table<schema.performance_schema.tables.records.FileSummaryByInstanceRecord> aliased) {
		this(alias, aliased, null);
	}

	private FileSummaryByInstance(java.lang.String alias, org.jooq.Table<schema.performance_schema.tables.records.FileSummaryByInstanceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.performance_schema.PerformanceSchema.PERFORMANCE_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.performance_schema.tables.FileSummaryByInstance as(java.lang.String alias) {
		return new schema.performance_schema.tables.FileSummaryByInstance(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.performance_schema.tables.FileSummaryByInstance rename(java.lang.String name) {
		return new schema.performance_schema.tables.FileSummaryByInstance(name, null);
	}
}
