/**
 * This class is generated by jOOQ
 */
package schema.performance_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MutexInstances extends org.jooq.impl.TableImpl<schema.performance_schema.tables.records.MutexInstancesRecord> {

	private static final long serialVersionUID = -1710391234;

	/**
	 * The reference instance of <code>performance_schema.mutex_instances</code>
	 */
	public static final schema.performance_schema.tables.MutexInstances MUTEX_INSTANCES = new schema.performance_schema.tables.MutexInstances();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.performance_schema.tables.records.MutexInstancesRecord> getRecordType() {
		return schema.performance_schema.tables.records.MutexInstancesRecord.class;
	}

	/**
	 * The column <code>performance_schema.mutex_instances.NAME</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.MutexInstancesRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>performance_schema.mutex_instances.OBJECT_INSTANCE_BEGIN</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.MutexInstancesRecord, java.lang.Long> OBJECT_INSTANCE_BEGIN = createField("OBJECT_INSTANCE_BEGIN", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>performance_schema.mutex_instances.LOCKED_BY_THREAD_ID</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.MutexInstancesRecord, java.lang.Integer> LOCKED_BY_THREAD_ID = createField("LOCKED_BY_THREAD_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>performance_schema.mutex_instances</code> table reference
	 */
	public MutexInstances() {
		this("mutex_instances", null);
	}

	/**
	 * Create an aliased <code>performance_schema.mutex_instances</code> table reference
	 */
	public MutexInstances(java.lang.String alias) {
		this(alias, schema.performance_schema.tables.MutexInstances.MUTEX_INSTANCES);
	}

	private MutexInstances(java.lang.String alias, org.jooq.Table<schema.performance_schema.tables.records.MutexInstancesRecord> aliased) {
		this(alias, aliased, null);
	}

	private MutexInstances(java.lang.String alias, org.jooq.Table<schema.performance_schema.tables.records.MutexInstancesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.performance_schema.PerformanceSchema.PERFORMANCE_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.performance_schema.tables.MutexInstances as(java.lang.String alias) {
		return new schema.performance_schema.tables.MutexInstances(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.performance_schema.tables.MutexInstances rename(java.lang.String name) {
		return new schema.performance_schema.tables.MutexInstances(name, null);
	}
}
