/**
 * This class is generated by jOOQ
 */
package schema.performance_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupConsumers extends org.jooq.impl.TableImpl<schema.performance_schema.tables.records.SetupConsumersRecord> {

	private static final long serialVersionUID = -1248892746;

	/**
	 * The reference instance of <code>performance_schema.setup_consumers</code>
	 */
	public static final schema.performance_schema.tables.SetupConsumers SETUP_CONSUMERS = new schema.performance_schema.tables.SetupConsumers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.performance_schema.tables.records.SetupConsumersRecord> getRecordType() {
		return schema.performance_schema.tables.records.SetupConsumersRecord.class;
	}

	/**
	 * The column <code>performance_schema.setup_consumers.NAME</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.SetupConsumersRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>performance_schema.setup_consumers.ENABLED</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.SetupConsumersRecord, schema.performance_schema.enums.SetupConsumersEnabled> ENABLED = createField("ENABLED", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(schema.performance_schema.enums.SetupConsumersEnabled.class), this, "");

	/**
	 * Create a <code>performance_schema.setup_consumers</code> table reference
	 */
	public SetupConsumers() {
		this("setup_consumers", null);
	}

	/**
	 * Create an aliased <code>performance_schema.setup_consumers</code> table reference
	 */
	public SetupConsumers(java.lang.String alias) {
		this(alias, schema.performance_schema.tables.SetupConsumers.SETUP_CONSUMERS);
	}

	private SetupConsumers(java.lang.String alias, org.jooq.Table<schema.performance_schema.tables.records.SetupConsumersRecord> aliased) {
		this(alias, aliased, null);
	}

	private SetupConsumers(java.lang.String alias, org.jooq.Table<schema.performance_schema.tables.records.SetupConsumersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.performance_schema.PerformanceSchema.PERFORMANCE_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.performance_schema.tables.SetupConsumers as(java.lang.String alias) {
		return new schema.performance_schema.tables.SetupConsumers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.performance_schema.tables.SetupConsumers rename(java.lang.String name) {
		return new schema.performance_schema.tables.SetupConsumers(name, null);
	}
}
