/**
 * This class is generated by jOOQ
 */
package schema.performance_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupInstruments extends org.jooq.impl.TableImpl<schema.performance_schema.tables.records.SetupInstrumentsRecord> {

	private static final long serialVersionUID = 2110979486;

	/**
	 * The reference instance of <code>performance_schema.setup_instruments</code>
	 */
	public static final schema.performance_schema.tables.SetupInstruments SETUP_INSTRUMENTS = new schema.performance_schema.tables.SetupInstruments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<schema.performance_schema.tables.records.SetupInstrumentsRecord> getRecordType() {
		return schema.performance_schema.tables.records.SetupInstrumentsRecord.class;
	}

	/**
	 * The column <code>performance_schema.setup_instruments.NAME</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.SetupInstrumentsRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>performance_schema.setup_instruments.ENABLED</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.SetupInstrumentsRecord, schema.performance_schema.enums.SetupInstrumentsEnabled> ENABLED = createField("ENABLED", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(schema.performance_schema.enums.SetupInstrumentsEnabled.class), this, "");

	/**
	 * The column <code>performance_schema.setup_instruments.TIMED</code>.
	 */
	public final org.jooq.TableField<schema.performance_schema.tables.records.SetupInstrumentsRecord, schema.performance_schema.enums.SetupInstrumentsTimed> TIMED = createField("TIMED", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(schema.performance_schema.enums.SetupInstrumentsTimed.class), this, "");

	/**
	 * Create a <code>performance_schema.setup_instruments</code> table reference
	 */
	public SetupInstruments() {
		this("setup_instruments", null);
	}

	/**
	 * Create an aliased <code>performance_schema.setup_instruments</code> table reference
	 */
	public SetupInstruments(java.lang.String alias) {
		this(alias, schema.performance_schema.tables.SetupInstruments.SETUP_INSTRUMENTS);
	}

	private SetupInstruments(java.lang.String alias, org.jooq.Table<schema.performance_schema.tables.records.SetupInstrumentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private SetupInstruments(java.lang.String alias, org.jooq.Table<schema.performance_schema.tables.records.SetupInstrumentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, schema.performance_schema.PerformanceSchema.PERFORMANCE_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public schema.performance_schema.tables.SetupInstruments as(java.lang.String alias) {
		return new schema.performance_schema.tables.SetupInstruments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public schema.performance_schema.tables.SetupInstruments rename(java.lang.String name) {
		return new schema.performance_schema.tables.SetupInstruments(name, null);
	}
}
