/**
 * This class is generated by jOOQ
 */
package cleandb.mysql.tables.records;

/**
 * Database privileges
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbRecord extends org.jooq.impl.UpdatableRecordImpl<cleandb.mysql.tables.records.DbRecord> implements org.jooq.Record22<java.lang.String, java.lang.String, java.lang.String, cleandb.mysql.enums.DbSelectPriv, cleandb.mysql.enums.DbInsertPriv, cleandb.mysql.enums.DbUpdatePriv, cleandb.mysql.enums.DbDeletePriv, cleandb.mysql.enums.DbCreatePriv, cleandb.mysql.enums.DbDropPriv, cleandb.mysql.enums.DbGrantPriv, cleandb.mysql.enums.DbReferencesPriv, cleandb.mysql.enums.DbIndexPriv, cleandb.mysql.enums.DbAlterPriv, cleandb.mysql.enums.DbCreateTmpTablePriv, cleandb.mysql.enums.DbLockTablesPriv, cleandb.mysql.enums.DbCreateViewPriv, cleandb.mysql.enums.DbShowViewPriv, cleandb.mysql.enums.DbCreateRoutinePriv, cleandb.mysql.enums.DbAlterRoutinePriv, cleandb.mysql.enums.DbExecutePriv, cleandb.mysql.enums.DbEventPriv, cleandb.mysql.enums.DbTriggerPriv> {

	private static final long serialVersionUID = 2082403700;

	/**
	 * Setter for <code>mysql.db.Host</code>.
	 */
	public void setHost(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mysql.db.Host</code>.
	 */
	public java.lang.String getHost() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>mysql.db.Db</code>.
	 */
	public void setDb(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mysql.db.Db</code>.
	 */
	public java.lang.String getDb() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>mysql.db.User</code>.
	 */
	public void setUser(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mysql.db.User</code>.
	 */
	public java.lang.String getUser() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>mysql.db.Select_priv</code>.
	 */
	public void setSelectPriv(cleandb.mysql.enums.DbSelectPriv value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mysql.db.Select_priv</code>.
	 */
	public cleandb.mysql.enums.DbSelectPriv getSelectPriv() {
		return (cleandb.mysql.enums.DbSelectPriv) getValue(3);
	}

	/**
	 * Setter for <code>mysql.db.Insert_priv</code>.
	 */
	public void setInsertPriv(cleandb.mysql.enums.DbInsertPriv value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mysql.db.Insert_priv</code>.
	 */
	public cleandb.mysql.enums.DbInsertPriv getInsertPriv() {
		return (cleandb.mysql.enums.DbInsertPriv) getValue(4);
	}

	/**
	 * Setter for <code>mysql.db.Update_priv</code>.
	 */
	public void setUpdatePriv(cleandb.mysql.enums.DbUpdatePriv value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mysql.db.Update_priv</code>.
	 */
	public cleandb.mysql.enums.DbUpdatePriv getUpdatePriv() {
		return (cleandb.mysql.enums.DbUpdatePriv) getValue(5);
	}

	/**
	 * Setter for <code>mysql.db.Delete_priv</code>.
	 */
	public void setDeletePriv(cleandb.mysql.enums.DbDeletePriv value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mysql.db.Delete_priv</code>.
	 */
	public cleandb.mysql.enums.DbDeletePriv getDeletePriv() {
		return (cleandb.mysql.enums.DbDeletePriv) getValue(6);
	}

	/**
	 * Setter for <code>mysql.db.Create_priv</code>.
	 */
	public void setCreatePriv(cleandb.mysql.enums.DbCreatePriv value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mysql.db.Create_priv</code>.
	 */
	public cleandb.mysql.enums.DbCreatePriv getCreatePriv() {
		return (cleandb.mysql.enums.DbCreatePriv) getValue(7);
	}

	/**
	 * Setter for <code>mysql.db.Drop_priv</code>.
	 */
	public void setDropPriv(cleandb.mysql.enums.DbDropPriv value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mysql.db.Drop_priv</code>.
	 */
	public cleandb.mysql.enums.DbDropPriv getDropPriv() {
		return (cleandb.mysql.enums.DbDropPriv) getValue(8);
	}

	/**
	 * Setter for <code>mysql.db.Grant_priv</code>.
	 */
	public void setGrantPriv(cleandb.mysql.enums.DbGrantPriv value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mysql.db.Grant_priv</code>.
	 */
	public cleandb.mysql.enums.DbGrantPriv getGrantPriv() {
		return (cleandb.mysql.enums.DbGrantPriv) getValue(9);
	}

	/**
	 * Setter for <code>mysql.db.References_priv</code>.
	 */
	public void setReferencesPriv(cleandb.mysql.enums.DbReferencesPriv value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>mysql.db.References_priv</code>.
	 */
	public cleandb.mysql.enums.DbReferencesPriv getReferencesPriv() {
		return (cleandb.mysql.enums.DbReferencesPriv) getValue(10);
	}

	/**
	 * Setter for <code>mysql.db.Index_priv</code>.
	 */
	public void setIndexPriv(cleandb.mysql.enums.DbIndexPriv value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>mysql.db.Index_priv</code>.
	 */
	public cleandb.mysql.enums.DbIndexPriv getIndexPriv() {
		return (cleandb.mysql.enums.DbIndexPriv) getValue(11);
	}

	/**
	 * Setter for <code>mysql.db.Alter_priv</code>.
	 */
	public void setAlterPriv(cleandb.mysql.enums.DbAlterPriv value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>mysql.db.Alter_priv</code>.
	 */
	public cleandb.mysql.enums.DbAlterPriv getAlterPriv() {
		return (cleandb.mysql.enums.DbAlterPriv) getValue(12);
	}

	/**
	 * Setter for <code>mysql.db.Create_tmp_table_priv</code>.
	 */
	public void setCreateTmpTablePriv(cleandb.mysql.enums.DbCreateTmpTablePriv value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>mysql.db.Create_tmp_table_priv</code>.
	 */
	public cleandb.mysql.enums.DbCreateTmpTablePriv getCreateTmpTablePriv() {
		return (cleandb.mysql.enums.DbCreateTmpTablePriv) getValue(13);
	}

	/**
	 * Setter for <code>mysql.db.Lock_tables_priv</code>.
	 */
	public void setLockTablesPriv(cleandb.mysql.enums.DbLockTablesPriv value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>mysql.db.Lock_tables_priv</code>.
	 */
	public cleandb.mysql.enums.DbLockTablesPriv getLockTablesPriv() {
		return (cleandb.mysql.enums.DbLockTablesPriv) getValue(14);
	}

	/**
	 * Setter for <code>mysql.db.Create_view_priv</code>.
	 */
	public void setCreateViewPriv(cleandb.mysql.enums.DbCreateViewPriv value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>mysql.db.Create_view_priv</code>.
	 */
	public cleandb.mysql.enums.DbCreateViewPriv getCreateViewPriv() {
		return (cleandb.mysql.enums.DbCreateViewPriv) getValue(15);
	}

	/**
	 * Setter for <code>mysql.db.Show_view_priv</code>.
	 */
	public void setShowViewPriv(cleandb.mysql.enums.DbShowViewPriv value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>mysql.db.Show_view_priv</code>.
	 */
	public cleandb.mysql.enums.DbShowViewPriv getShowViewPriv() {
		return (cleandb.mysql.enums.DbShowViewPriv) getValue(16);
	}

	/**
	 * Setter for <code>mysql.db.Create_routine_priv</code>.
	 */
	public void setCreateRoutinePriv(cleandb.mysql.enums.DbCreateRoutinePriv value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>mysql.db.Create_routine_priv</code>.
	 */
	public cleandb.mysql.enums.DbCreateRoutinePriv getCreateRoutinePriv() {
		return (cleandb.mysql.enums.DbCreateRoutinePriv) getValue(17);
	}

	/**
	 * Setter for <code>mysql.db.Alter_routine_priv</code>.
	 */
	public void setAlterRoutinePriv(cleandb.mysql.enums.DbAlterRoutinePriv value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>mysql.db.Alter_routine_priv</code>.
	 */
	public cleandb.mysql.enums.DbAlterRoutinePriv getAlterRoutinePriv() {
		return (cleandb.mysql.enums.DbAlterRoutinePriv) getValue(18);
	}

	/**
	 * Setter for <code>mysql.db.Execute_priv</code>.
	 */
	public void setExecutePriv(cleandb.mysql.enums.DbExecutePriv value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>mysql.db.Execute_priv</code>.
	 */
	public cleandb.mysql.enums.DbExecutePriv getExecutePriv() {
		return (cleandb.mysql.enums.DbExecutePriv) getValue(19);
	}

	/**
	 * Setter for <code>mysql.db.Event_priv</code>.
	 */
	public void setEventPriv(cleandb.mysql.enums.DbEventPriv value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>mysql.db.Event_priv</code>.
	 */
	public cleandb.mysql.enums.DbEventPriv getEventPriv() {
		return (cleandb.mysql.enums.DbEventPriv) getValue(20);
	}

	/**
	 * Setter for <code>mysql.db.Trigger_priv</code>.
	 */
	public void setTriggerPriv(cleandb.mysql.enums.DbTriggerPriv value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>mysql.db.Trigger_priv</code>.
	 */
	public cleandb.mysql.enums.DbTriggerPriv getTriggerPriv() {
		return (cleandb.mysql.enums.DbTriggerPriv) getValue(21);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.String, java.lang.String, java.lang.String> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record22 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<java.lang.String, java.lang.String, java.lang.String, cleandb.mysql.enums.DbSelectPriv, cleandb.mysql.enums.DbInsertPriv, cleandb.mysql.enums.DbUpdatePriv, cleandb.mysql.enums.DbDeletePriv, cleandb.mysql.enums.DbCreatePriv, cleandb.mysql.enums.DbDropPriv, cleandb.mysql.enums.DbGrantPriv, cleandb.mysql.enums.DbReferencesPriv, cleandb.mysql.enums.DbIndexPriv, cleandb.mysql.enums.DbAlterPriv, cleandb.mysql.enums.DbCreateTmpTablePriv, cleandb.mysql.enums.DbLockTablesPriv, cleandb.mysql.enums.DbCreateViewPriv, cleandb.mysql.enums.DbShowViewPriv, cleandb.mysql.enums.DbCreateRoutinePriv, cleandb.mysql.enums.DbAlterRoutinePriv, cleandb.mysql.enums.DbExecutePriv, cleandb.mysql.enums.DbEventPriv, cleandb.mysql.enums.DbTriggerPriv> fieldsRow() {
		return (org.jooq.Row22) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row22<java.lang.String, java.lang.String, java.lang.String, cleandb.mysql.enums.DbSelectPriv, cleandb.mysql.enums.DbInsertPriv, cleandb.mysql.enums.DbUpdatePriv, cleandb.mysql.enums.DbDeletePriv, cleandb.mysql.enums.DbCreatePriv, cleandb.mysql.enums.DbDropPriv, cleandb.mysql.enums.DbGrantPriv, cleandb.mysql.enums.DbReferencesPriv, cleandb.mysql.enums.DbIndexPriv, cleandb.mysql.enums.DbAlterPriv, cleandb.mysql.enums.DbCreateTmpTablePriv, cleandb.mysql.enums.DbLockTablesPriv, cleandb.mysql.enums.DbCreateViewPriv, cleandb.mysql.enums.DbShowViewPriv, cleandb.mysql.enums.DbCreateRoutinePriv, cleandb.mysql.enums.DbAlterRoutinePriv, cleandb.mysql.enums.DbExecutePriv, cleandb.mysql.enums.DbEventPriv, cleandb.mysql.enums.DbTriggerPriv> valuesRow() {
		return (org.jooq.Row22) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return cleandb.mysql.tables.Db.DB.HOST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cleandb.mysql.tables.Db.DB.DB_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return cleandb.mysql.tables.Db.DB.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbSelectPriv> field4() {
		return cleandb.mysql.tables.Db.DB.SELECT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbInsertPriv> field5() {
		return cleandb.mysql.tables.Db.DB.INSERT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbUpdatePriv> field6() {
		return cleandb.mysql.tables.Db.DB.UPDATE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbDeletePriv> field7() {
		return cleandb.mysql.tables.Db.DB.DELETE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbCreatePriv> field8() {
		return cleandb.mysql.tables.Db.DB.CREATE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbDropPriv> field9() {
		return cleandb.mysql.tables.Db.DB.DROP_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbGrantPriv> field10() {
		return cleandb.mysql.tables.Db.DB.GRANT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbReferencesPriv> field11() {
		return cleandb.mysql.tables.Db.DB.REFERENCES_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbIndexPriv> field12() {
		return cleandb.mysql.tables.Db.DB.INDEX_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbAlterPriv> field13() {
		return cleandb.mysql.tables.Db.DB.ALTER_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbCreateTmpTablePriv> field14() {
		return cleandb.mysql.tables.Db.DB.CREATE_TMP_TABLE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbLockTablesPriv> field15() {
		return cleandb.mysql.tables.Db.DB.LOCK_TABLES_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbCreateViewPriv> field16() {
		return cleandb.mysql.tables.Db.DB.CREATE_VIEW_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbShowViewPriv> field17() {
		return cleandb.mysql.tables.Db.DB.SHOW_VIEW_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbCreateRoutinePriv> field18() {
		return cleandb.mysql.tables.Db.DB.CREATE_ROUTINE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbAlterRoutinePriv> field19() {
		return cleandb.mysql.tables.Db.DB.ALTER_ROUTINE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbExecutePriv> field20() {
		return cleandb.mysql.tables.Db.DB.EXECUTE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbEventPriv> field21() {
		return cleandb.mysql.tables.Db.DB.EVENT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.DbTriggerPriv> field22() {
		return cleandb.mysql.tables.Db.DB.TRIGGER_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getHost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDb();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbSelectPriv value4() {
		return getSelectPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbInsertPriv value5() {
		return getInsertPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbUpdatePriv value6() {
		return getUpdatePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbDeletePriv value7() {
		return getDeletePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbCreatePriv value8() {
		return getCreatePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbDropPriv value9() {
		return getDropPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbGrantPriv value10() {
		return getGrantPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbReferencesPriv value11() {
		return getReferencesPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbIndexPriv value12() {
		return getIndexPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbAlterPriv value13() {
		return getAlterPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbCreateTmpTablePriv value14() {
		return getCreateTmpTablePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbLockTablesPriv value15() {
		return getLockTablesPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbCreateViewPriv value16() {
		return getCreateViewPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbShowViewPriv value17() {
		return getShowViewPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbCreateRoutinePriv value18() {
		return getCreateRoutinePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbAlterRoutinePriv value19() {
		return getAlterRoutinePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbExecutePriv value20() {
		return getExecutePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbEventPriv value21() {
		return getEventPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.DbTriggerPriv value22() {
		return getTriggerPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value1(java.lang.String value) {
		setHost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value2(java.lang.String value) {
		setDb(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value3(java.lang.String value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value4(cleandb.mysql.enums.DbSelectPriv value) {
		setSelectPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value5(cleandb.mysql.enums.DbInsertPriv value) {
		setInsertPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value6(cleandb.mysql.enums.DbUpdatePriv value) {
		setUpdatePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value7(cleandb.mysql.enums.DbDeletePriv value) {
		setDeletePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value8(cleandb.mysql.enums.DbCreatePriv value) {
		setCreatePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value9(cleandb.mysql.enums.DbDropPriv value) {
		setDropPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value10(cleandb.mysql.enums.DbGrantPriv value) {
		setGrantPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value11(cleandb.mysql.enums.DbReferencesPriv value) {
		setReferencesPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value12(cleandb.mysql.enums.DbIndexPriv value) {
		setIndexPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value13(cleandb.mysql.enums.DbAlterPriv value) {
		setAlterPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value14(cleandb.mysql.enums.DbCreateTmpTablePriv value) {
		setCreateTmpTablePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value15(cleandb.mysql.enums.DbLockTablesPriv value) {
		setLockTablesPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value16(cleandb.mysql.enums.DbCreateViewPriv value) {
		setCreateViewPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value17(cleandb.mysql.enums.DbShowViewPriv value) {
		setShowViewPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value18(cleandb.mysql.enums.DbCreateRoutinePriv value) {
		setCreateRoutinePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value19(cleandb.mysql.enums.DbAlterRoutinePriv value) {
		setAlterRoutinePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value20(cleandb.mysql.enums.DbExecutePriv value) {
		setExecutePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value21(cleandb.mysql.enums.DbEventPriv value) {
		setEventPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord value22(cleandb.mysql.enums.DbTriggerPriv value) {
		setTriggerPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DbRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, cleandb.mysql.enums.DbSelectPriv value4, cleandb.mysql.enums.DbInsertPriv value5, cleandb.mysql.enums.DbUpdatePriv value6, cleandb.mysql.enums.DbDeletePriv value7, cleandb.mysql.enums.DbCreatePriv value8, cleandb.mysql.enums.DbDropPriv value9, cleandb.mysql.enums.DbGrantPriv value10, cleandb.mysql.enums.DbReferencesPriv value11, cleandb.mysql.enums.DbIndexPriv value12, cleandb.mysql.enums.DbAlterPriv value13, cleandb.mysql.enums.DbCreateTmpTablePriv value14, cleandb.mysql.enums.DbLockTablesPriv value15, cleandb.mysql.enums.DbCreateViewPriv value16, cleandb.mysql.enums.DbShowViewPriv value17, cleandb.mysql.enums.DbCreateRoutinePriv value18, cleandb.mysql.enums.DbAlterRoutinePriv value19, cleandb.mysql.enums.DbExecutePriv value20, cleandb.mysql.enums.DbEventPriv value21, cleandb.mysql.enums.DbTriggerPriv value22) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DbRecord
	 */
	public DbRecord() {
		super(cleandb.mysql.tables.Db.DB);
	}

	/**
	 * Create a detached, initialised DbRecord
	 */
	public DbRecord(java.lang.String host, java.lang.String db, java.lang.String user, cleandb.mysql.enums.DbSelectPriv selectPriv, cleandb.mysql.enums.DbInsertPriv insertPriv, cleandb.mysql.enums.DbUpdatePriv updatePriv, cleandb.mysql.enums.DbDeletePriv deletePriv, cleandb.mysql.enums.DbCreatePriv createPriv, cleandb.mysql.enums.DbDropPriv dropPriv, cleandb.mysql.enums.DbGrantPriv grantPriv, cleandb.mysql.enums.DbReferencesPriv referencesPriv, cleandb.mysql.enums.DbIndexPriv indexPriv, cleandb.mysql.enums.DbAlterPriv alterPriv, cleandb.mysql.enums.DbCreateTmpTablePriv createTmpTablePriv, cleandb.mysql.enums.DbLockTablesPriv lockTablesPriv, cleandb.mysql.enums.DbCreateViewPriv createViewPriv, cleandb.mysql.enums.DbShowViewPriv showViewPriv, cleandb.mysql.enums.DbCreateRoutinePriv createRoutinePriv, cleandb.mysql.enums.DbAlterRoutinePriv alterRoutinePriv, cleandb.mysql.enums.DbExecutePriv executePriv, cleandb.mysql.enums.DbEventPriv eventPriv, cleandb.mysql.enums.DbTriggerPriv triggerPriv) {
		super(cleandb.mysql.tables.Db.DB);

		setValue(0, host);
		setValue(1, db);
		setValue(2, user);
		setValue(3, selectPriv);
		setValue(4, insertPriv);
		setValue(5, updatePriv);
		setValue(6, deletePriv);
		setValue(7, createPriv);
		setValue(8, dropPriv);
		setValue(9, grantPriv);
		setValue(10, referencesPriv);
		setValue(11, indexPriv);
		setValue(12, alterPriv);
		setValue(13, createTmpTablePriv);
		setValue(14, lockTablesPriv);
		setValue(15, createViewPriv);
		setValue(16, showViewPriv);
		setValue(17, createRoutinePriv);
		setValue(18, alterRoutinePriv);
		setValue(19, executePriv);
		setValue(20, eventPriv);
		setValue(21, triggerPriv);
	}
}
