/**
 * This class is generated by jOOQ
 */
package cleandb.mysql.tables.records;

/**
 * Host privileges;  Merged with database privileges
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostRecord extends org.jooq.impl.UpdatableRecordImpl<cleandb.mysql.tables.records.HostRecord> implements org.jooq.Record20<java.lang.String, java.lang.String, cleandb.mysql.enums.HostSelectPriv, cleandb.mysql.enums.HostInsertPriv, cleandb.mysql.enums.HostUpdatePriv, cleandb.mysql.enums.HostDeletePriv, cleandb.mysql.enums.HostCreatePriv, cleandb.mysql.enums.HostDropPriv, cleandb.mysql.enums.HostGrantPriv, cleandb.mysql.enums.HostReferencesPriv, cleandb.mysql.enums.HostIndexPriv, cleandb.mysql.enums.HostAlterPriv, cleandb.mysql.enums.HostCreateTmpTablePriv, cleandb.mysql.enums.HostLockTablesPriv, cleandb.mysql.enums.HostCreateViewPriv, cleandb.mysql.enums.HostShowViewPriv, cleandb.mysql.enums.HostCreateRoutinePriv, cleandb.mysql.enums.HostAlterRoutinePriv, cleandb.mysql.enums.HostExecutePriv, cleandb.mysql.enums.HostTriggerPriv> {

	private static final long serialVersionUID = 1062807139;

	/**
	 * Setter for <code>mysql.host.Host</code>.
	 */
	public void setHost(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mysql.host.Host</code>.
	 */
	public java.lang.String getHost() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>mysql.host.Db</code>.
	 */
	public void setDb(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mysql.host.Db</code>.
	 */
	public java.lang.String getDb() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>mysql.host.Select_priv</code>.
	 */
	public void setSelectPriv(cleandb.mysql.enums.HostSelectPriv value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mysql.host.Select_priv</code>.
	 */
	public cleandb.mysql.enums.HostSelectPriv getSelectPriv() {
		return (cleandb.mysql.enums.HostSelectPriv) getValue(2);
	}

	/**
	 * Setter for <code>mysql.host.Insert_priv</code>.
	 */
	public void setInsertPriv(cleandb.mysql.enums.HostInsertPriv value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mysql.host.Insert_priv</code>.
	 */
	public cleandb.mysql.enums.HostInsertPriv getInsertPriv() {
		return (cleandb.mysql.enums.HostInsertPriv) getValue(3);
	}

	/**
	 * Setter for <code>mysql.host.Update_priv</code>.
	 */
	public void setUpdatePriv(cleandb.mysql.enums.HostUpdatePriv value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mysql.host.Update_priv</code>.
	 */
	public cleandb.mysql.enums.HostUpdatePriv getUpdatePriv() {
		return (cleandb.mysql.enums.HostUpdatePriv) getValue(4);
	}

	/**
	 * Setter for <code>mysql.host.Delete_priv</code>.
	 */
	public void setDeletePriv(cleandb.mysql.enums.HostDeletePriv value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mysql.host.Delete_priv</code>.
	 */
	public cleandb.mysql.enums.HostDeletePriv getDeletePriv() {
		return (cleandb.mysql.enums.HostDeletePriv) getValue(5);
	}

	/**
	 * Setter for <code>mysql.host.Create_priv</code>.
	 */
	public void setCreatePriv(cleandb.mysql.enums.HostCreatePriv value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mysql.host.Create_priv</code>.
	 */
	public cleandb.mysql.enums.HostCreatePriv getCreatePriv() {
		return (cleandb.mysql.enums.HostCreatePriv) getValue(6);
	}

	/**
	 * Setter for <code>mysql.host.Drop_priv</code>.
	 */
	public void setDropPriv(cleandb.mysql.enums.HostDropPriv value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mysql.host.Drop_priv</code>.
	 */
	public cleandb.mysql.enums.HostDropPriv getDropPriv() {
		return (cleandb.mysql.enums.HostDropPriv) getValue(7);
	}

	/**
	 * Setter for <code>mysql.host.Grant_priv</code>.
	 */
	public void setGrantPriv(cleandb.mysql.enums.HostGrantPriv value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mysql.host.Grant_priv</code>.
	 */
	public cleandb.mysql.enums.HostGrantPriv getGrantPriv() {
		return (cleandb.mysql.enums.HostGrantPriv) getValue(8);
	}

	/**
	 * Setter for <code>mysql.host.References_priv</code>.
	 */
	public void setReferencesPriv(cleandb.mysql.enums.HostReferencesPriv value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mysql.host.References_priv</code>.
	 */
	public cleandb.mysql.enums.HostReferencesPriv getReferencesPriv() {
		return (cleandb.mysql.enums.HostReferencesPriv) getValue(9);
	}

	/**
	 * Setter for <code>mysql.host.Index_priv</code>.
	 */
	public void setIndexPriv(cleandb.mysql.enums.HostIndexPriv value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>mysql.host.Index_priv</code>.
	 */
	public cleandb.mysql.enums.HostIndexPriv getIndexPriv() {
		return (cleandb.mysql.enums.HostIndexPriv) getValue(10);
	}

	/**
	 * Setter for <code>mysql.host.Alter_priv</code>.
	 */
	public void setAlterPriv(cleandb.mysql.enums.HostAlterPriv value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>mysql.host.Alter_priv</code>.
	 */
	public cleandb.mysql.enums.HostAlterPriv getAlterPriv() {
		return (cleandb.mysql.enums.HostAlterPriv) getValue(11);
	}

	/**
	 * Setter for <code>mysql.host.Create_tmp_table_priv</code>.
	 */
	public void setCreateTmpTablePriv(cleandb.mysql.enums.HostCreateTmpTablePriv value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>mysql.host.Create_tmp_table_priv</code>.
	 */
	public cleandb.mysql.enums.HostCreateTmpTablePriv getCreateTmpTablePriv() {
		return (cleandb.mysql.enums.HostCreateTmpTablePriv) getValue(12);
	}

	/**
	 * Setter for <code>mysql.host.Lock_tables_priv</code>.
	 */
	public void setLockTablesPriv(cleandb.mysql.enums.HostLockTablesPriv value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>mysql.host.Lock_tables_priv</code>.
	 */
	public cleandb.mysql.enums.HostLockTablesPriv getLockTablesPriv() {
		return (cleandb.mysql.enums.HostLockTablesPriv) getValue(13);
	}

	/**
	 * Setter for <code>mysql.host.Create_view_priv</code>.
	 */
	public void setCreateViewPriv(cleandb.mysql.enums.HostCreateViewPriv value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>mysql.host.Create_view_priv</code>.
	 */
	public cleandb.mysql.enums.HostCreateViewPriv getCreateViewPriv() {
		return (cleandb.mysql.enums.HostCreateViewPriv) getValue(14);
	}

	/**
	 * Setter for <code>mysql.host.Show_view_priv</code>.
	 */
	public void setShowViewPriv(cleandb.mysql.enums.HostShowViewPriv value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>mysql.host.Show_view_priv</code>.
	 */
	public cleandb.mysql.enums.HostShowViewPriv getShowViewPriv() {
		return (cleandb.mysql.enums.HostShowViewPriv) getValue(15);
	}

	/**
	 * Setter for <code>mysql.host.Create_routine_priv</code>.
	 */
	public void setCreateRoutinePriv(cleandb.mysql.enums.HostCreateRoutinePriv value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>mysql.host.Create_routine_priv</code>.
	 */
	public cleandb.mysql.enums.HostCreateRoutinePriv getCreateRoutinePriv() {
		return (cleandb.mysql.enums.HostCreateRoutinePriv) getValue(16);
	}

	/**
	 * Setter for <code>mysql.host.Alter_routine_priv</code>.
	 */
	public void setAlterRoutinePriv(cleandb.mysql.enums.HostAlterRoutinePriv value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>mysql.host.Alter_routine_priv</code>.
	 */
	public cleandb.mysql.enums.HostAlterRoutinePriv getAlterRoutinePriv() {
		return (cleandb.mysql.enums.HostAlterRoutinePriv) getValue(17);
	}

	/**
	 * Setter for <code>mysql.host.Execute_priv</code>.
	 */
	public void setExecutePriv(cleandb.mysql.enums.HostExecutePriv value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>mysql.host.Execute_priv</code>.
	 */
	public cleandb.mysql.enums.HostExecutePriv getExecutePriv() {
		return (cleandb.mysql.enums.HostExecutePriv) getValue(18);
	}

	/**
	 * Setter for <code>mysql.host.Trigger_priv</code>.
	 */
	public void setTriggerPriv(cleandb.mysql.enums.HostTriggerPriv value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>mysql.host.Trigger_priv</code>.
	 */
	public cleandb.mysql.enums.HostTriggerPriv getTriggerPriv() {
		return (cleandb.mysql.enums.HostTriggerPriv) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.String, java.lang.String, cleandb.mysql.enums.HostSelectPriv, cleandb.mysql.enums.HostInsertPriv, cleandb.mysql.enums.HostUpdatePriv, cleandb.mysql.enums.HostDeletePriv, cleandb.mysql.enums.HostCreatePriv, cleandb.mysql.enums.HostDropPriv, cleandb.mysql.enums.HostGrantPriv, cleandb.mysql.enums.HostReferencesPriv, cleandb.mysql.enums.HostIndexPriv, cleandb.mysql.enums.HostAlterPriv, cleandb.mysql.enums.HostCreateTmpTablePriv, cleandb.mysql.enums.HostLockTablesPriv, cleandb.mysql.enums.HostCreateViewPriv, cleandb.mysql.enums.HostShowViewPriv, cleandb.mysql.enums.HostCreateRoutinePriv, cleandb.mysql.enums.HostAlterRoutinePriv, cleandb.mysql.enums.HostExecutePriv, cleandb.mysql.enums.HostTriggerPriv> fieldsRow() {
		return (org.jooq.Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.String, java.lang.String, cleandb.mysql.enums.HostSelectPriv, cleandb.mysql.enums.HostInsertPriv, cleandb.mysql.enums.HostUpdatePriv, cleandb.mysql.enums.HostDeletePriv, cleandb.mysql.enums.HostCreatePriv, cleandb.mysql.enums.HostDropPriv, cleandb.mysql.enums.HostGrantPriv, cleandb.mysql.enums.HostReferencesPriv, cleandb.mysql.enums.HostIndexPriv, cleandb.mysql.enums.HostAlterPriv, cleandb.mysql.enums.HostCreateTmpTablePriv, cleandb.mysql.enums.HostLockTablesPriv, cleandb.mysql.enums.HostCreateViewPriv, cleandb.mysql.enums.HostShowViewPriv, cleandb.mysql.enums.HostCreateRoutinePriv, cleandb.mysql.enums.HostAlterRoutinePriv, cleandb.mysql.enums.HostExecutePriv, cleandb.mysql.enums.HostTriggerPriv> valuesRow() {
		return (org.jooq.Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return cleandb.mysql.tables.Host.HOST.HOST_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cleandb.mysql.tables.Host.HOST.DB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostSelectPriv> field3() {
		return cleandb.mysql.tables.Host.HOST.SELECT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostInsertPriv> field4() {
		return cleandb.mysql.tables.Host.HOST.INSERT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostUpdatePriv> field5() {
		return cleandb.mysql.tables.Host.HOST.UPDATE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostDeletePriv> field6() {
		return cleandb.mysql.tables.Host.HOST.DELETE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostCreatePriv> field7() {
		return cleandb.mysql.tables.Host.HOST.CREATE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostDropPriv> field8() {
		return cleandb.mysql.tables.Host.HOST.DROP_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostGrantPriv> field9() {
		return cleandb.mysql.tables.Host.HOST.GRANT_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostReferencesPriv> field10() {
		return cleandb.mysql.tables.Host.HOST.REFERENCES_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostIndexPriv> field11() {
		return cleandb.mysql.tables.Host.HOST.INDEX_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostAlterPriv> field12() {
		return cleandb.mysql.tables.Host.HOST.ALTER_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostCreateTmpTablePriv> field13() {
		return cleandb.mysql.tables.Host.HOST.CREATE_TMP_TABLE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostLockTablesPriv> field14() {
		return cleandb.mysql.tables.Host.HOST.LOCK_TABLES_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostCreateViewPriv> field15() {
		return cleandb.mysql.tables.Host.HOST.CREATE_VIEW_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostShowViewPriv> field16() {
		return cleandb.mysql.tables.Host.HOST.SHOW_VIEW_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostCreateRoutinePriv> field17() {
		return cleandb.mysql.tables.Host.HOST.CREATE_ROUTINE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostAlterRoutinePriv> field18() {
		return cleandb.mysql.tables.Host.HOST.ALTER_ROUTINE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostExecutePriv> field19() {
		return cleandb.mysql.tables.Host.HOST.EXECUTE_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<cleandb.mysql.enums.HostTriggerPriv> field20() {
		return cleandb.mysql.tables.Host.HOST.TRIGGER_PRIV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getHost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDb();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostSelectPriv value3() {
		return getSelectPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostInsertPriv value4() {
		return getInsertPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostUpdatePriv value5() {
		return getUpdatePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostDeletePriv value6() {
		return getDeletePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostCreatePriv value7() {
		return getCreatePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostDropPriv value8() {
		return getDropPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostGrantPriv value9() {
		return getGrantPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostReferencesPriv value10() {
		return getReferencesPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostIndexPriv value11() {
		return getIndexPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostAlterPriv value12() {
		return getAlterPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostCreateTmpTablePriv value13() {
		return getCreateTmpTablePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostLockTablesPriv value14() {
		return getLockTablesPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostCreateViewPriv value15() {
		return getCreateViewPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostShowViewPriv value16() {
		return getShowViewPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostCreateRoutinePriv value17() {
		return getCreateRoutinePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostAlterRoutinePriv value18() {
		return getAlterRoutinePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostExecutePriv value19() {
		return getExecutePriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.enums.HostTriggerPriv value20() {
		return getTriggerPriv();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value1(java.lang.String value) {
		setHost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value2(java.lang.String value) {
		setDb(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value3(cleandb.mysql.enums.HostSelectPriv value) {
		setSelectPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value4(cleandb.mysql.enums.HostInsertPriv value) {
		setInsertPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value5(cleandb.mysql.enums.HostUpdatePriv value) {
		setUpdatePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value6(cleandb.mysql.enums.HostDeletePriv value) {
		setDeletePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value7(cleandb.mysql.enums.HostCreatePriv value) {
		setCreatePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value8(cleandb.mysql.enums.HostDropPriv value) {
		setDropPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value9(cleandb.mysql.enums.HostGrantPriv value) {
		setGrantPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value10(cleandb.mysql.enums.HostReferencesPriv value) {
		setReferencesPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value11(cleandb.mysql.enums.HostIndexPriv value) {
		setIndexPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value12(cleandb.mysql.enums.HostAlterPriv value) {
		setAlterPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value13(cleandb.mysql.enums.HostCreateTmpTablePriv value) {
		setCreateTmpTablePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value14(cleandb.mysql.enums.HostLockTablesPriv value) {
		setLockTablesPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value15(cleandb.mysql.enums.HostCreateViewPriv value) {
		setCreateViewPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value16(cleandb.mysql.enums.HostShowViewPriv value) {
		setShowViewPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value17(cleandb.mysql.enums.HostCreateRoutinePriv value) {
		setCreateRoutinePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value18(cleandb.mysql.enums.HostAlterRoutinePriv value) {
		setAlterRoutinePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value19(cleandb.mysql.enums.HostExecutePriv value) {
		setExecutePriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord value20(cleandb.mysql.enums.HostTriggerPriv value) {
		setTriggerPriv(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HostRecord values(java.lang.String value1, java.lang.String value2, cleandb.mysql.enums.HostSelectPriv value3, cleandb.mysql.enums.HostInsertPriv value4, cleandb.mysql.enums.HostUpdatePriv value5, cleandb.mysql.enums.HostDeletePriv value6, cleandb.mysql.enums.HostCreatePriv value7, cleandb.mysql.enums.HostDropPriv value8, cleandb.mysql.enums.HostGrantPriv value9, cleandb.mysql.enums.HostReferencesPriv value10, cleandb.mysql.enums.HostIndexPriv value11, cleandb.mysql.enums.HostAlterPriv value12, cleandb.mysql.enums.HostCreateTmpTablePriv value13, cleandb.mysql.enums.HostLockTablesPriv value14, cleandb.mysql.enums.HostCreateViewPriv value15, cleandb.mysql.enums.HostShowViewPriv value16, cleandb.mysql.enums.HostCreateRoutinePriv value17, cleandb.mysql.enums.HostAlterRoutinePriv value18, cleandb.mysql.enums.HostExecutePriv value19, cleandb.mysql.enums.HostTriggerPriv value20) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HostRecord
	 */
	public HostRecord() {
		super(cleandb.mysql.tables.Host.HOST);
	}

	/**
	 * Create a detached, initialised HostRecord
	 */
	public HostRecord(java.lang.String host, java.lang.String db, cleandb.mysql.enums.HostSelectPriv selectPriv, cleandb.mysql.enums.HostInsertPriv insertPriv, cleandb.mysql.enums.HostUpdatePriv updatePriv, cleandb.mysql.enums.HostDeletePriv deletePriv, cleandb.mysql.enums.HostCreatePriv createPriv, cleandb.mysql.enums.HostDropPriv dropPriv, cleandb.mysql.enums.HostGrantPriv grantPriv, cleandb.mysql.enums.HostReferencesPriv referencesPriv, cleandb.mysql.enums.HostIndexPriv indexPriv, cleandb.mysql.enums.HostAlterPriv alterPriv, cleandb.mysql.enums.HostCreateTmpTablePriv createTmpTablePriv, cleandb.mysql.enums.HostLockTablesPriv lockTablesPriv, cleandb.mysql.enums.HostCreateViewPriv createViewPriv, cleandb.mysql.enums.HostShowViewPriv showViewPriv, cleandb.mysql.enums.HostCreateRoutinePriv createRoutinePriv, cleandb.mysql.enums.HostAlterRoutinePriv alterRoutinePriv, cleandb.mysql.enums.HostExecutePriv executePriv, cleandb.mysql.enums.HostTriggerPriv triggerPriv) {
		super(cleandb.mysql.tables.Host.HOST);

		setValue(0, host);
		setValue(1, db);
		setValue(2, selectPriv);
		setValue(3, insertPriv);
		setValue(4, updatePriv);
		setValue(5, deletePriv);
		setValue(6, createPriv);
		setValue(7, dropPriv);
		setValue(8, grantPriv);
		setValue(9, referencesPriv);
		setValue(10, indexPriv);
		setValue(11, alterPriv);
		setValue(12, createTmpTablePriv);
		setValue(13, lockTablesPriv);
		setValue(14, createViewPriv);
		setValue(15, showViewPriv);
		setValue(16, createRoutinePriv);
		setValue(17, alterRoutinePriv);
		setValue(18, executePriv);
		setValue(19, triggerPriv);
	}
}
