/**
 * This class is generated by jOOQ
 */
package cleandb.mysql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NdbBinlogIndexRecord extends org.jooq.impl.UpdatableRecordImpl<cleandb.mysql.tables.records.NdbBinlogIndexRecord> implements org.jooq.Record7<org.jooq.types.ULong, java.lang.String, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong> {

	private static final long serialVersionUID = 1328940130;

	/**
	 * Setter for <code>mysql.ndb_binlog_index.Position</code>.
	 */
	public void setPosition(org.jooq.types.ULong value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mysql.ndb_binlog_index.Position</code>.
	 */
	public org.jooq.types.ULong getPosition() {
		return (org.jooq.types.ULong) getValue(0);
	}

	/**
	 * Setter for <code>mysql.ndb_binlog_index.File</code>.
	 */
	public void setFile(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mysql.ndb_binlog_index.File</code>.
	 */
	public java.lang.String getFile() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>mysql.ndb_binlog_index.epoch</code>.
	 */
	public void setEpoch(org.jooq.types.ULong value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mysql.ndb_binlog_index.epoch</code>.
	 */
	public org.jooq.types.ULong getEpoch() {
		return (org.jooq.types.ULong) getValue(2);
	}

	/**
	 * Setter for <code>mysql.ndb_binlog_index.inserts</code>.
	 */
	public void setInserts(org.jooq.types.ULong value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mysql.ndb_binlog_index.inserts</code>.
	 */
	public org.jooq.types.ULong getInserts() {
		return (org.jooq.types.ULong) getValue(3);
	}

	/**
	 * Setter for <code>mysql.ndb_binlog_index.updates</code>.
	 */
	public void setUpdates(org.jooq.types.ULong value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mysql.ndb_binlog_index.updates</code>.
	 */
	public org.jooq.types.ULong getUpdates() {
		return (org.jooq.types.ULong) getValue(4);
	}

	/**
	 * Setter for <code>mysql.ndb_binlog_index.deletes</code>.
	 */
	public void setDeletes(org.jooq.types.ULong value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mysql.ndb_binlog_index.deletes</code>.
	 */
	public org.jooq.types.ULong getDeletes() {
		return (org.jooq.types.ULong) getValue(5);
	}

	/**
	 * Setter for <code>mysql.ndb_binlog_index.schemaops</code>.
	 */
	public void setSchemaops(org.jooq.types.ULong value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mysql.ndb_binlog_index.schemaops</code>.
	 */
	public org.jooq.types.ULong getSchemaops() {
		return (org.jooq.types.ULong) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.ULong> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<org.jooq.types.ULong, java.lang.String, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<org.jooq.types.ULong, java.lang.String, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong, org.jooq.types.ULong> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field1() {
		return cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX.POSITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX.FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field3() {
		return cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX.EPOCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field4() {
		return cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX.INSERTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field5() {
		return cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX.UPDATES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field6() {
		return cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX.DELETES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.ULong> field7() {
		return cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX.SCHEMAOPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value1() {
		return getPosition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value3() {
		return getEpoch();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value4() {
		return getInserts();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value5() {
		return getUpdates();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value6() {
		return getDeletes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.ULong value7() {
		return getSchemaops();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NdbBinlogIndexRecord value1(org.jooq.types.ULong value) {
		setPosition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NdbBinlogIndexRecord value2(java.lang.String value) {
		setFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NdbBinlogIndexRecord value3(org.jooq.types.ULong value) {
		setEpoch(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NdbBinlogIndexRecord value4(org.jooq.types.ULong value) {
		setInserts(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NdbBinlogIndexRecord value5(org.jooq.types.ULong value) {
		setUpdates(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NdbBinlogIndexRecord value6(org.jooq.types.ULong value) {
		setDeletes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NdbBinlogIndexRecord value7(org.jooq.types.ULong value) {
		setSchemaops(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NdbBinlogIndexRecord values(org.jooq.types.ULong value1, java.lang.String value2, org.jooq.types.ULong value3, org.jooq.types.ULong value4, org.jooq.types.ULong value5, org.jooq.types.ULong value6, org.jooq.types.ULong value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NdbBinlogIndexRecord
	 */
	public NdbBinlogIndexRecord() {
		super(cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX);
	}

	/**
	 * Create a detached, initialised NdbBinlogIndexRecord
	 */
	public NdbBinlogIndexRecord(org.jooq.types.ULong position, java.lang.String file, org.jooq.types.ULong epoch, org.jooq.types.ULong inserts, org.jooq.types.ULong updates, org.jooq.types.ULong deletes, org.jooq.types.ULong schemaops) {
		super(cleandb.mysql.tables.NdbBinlogIndex.NDB_BINLOG_INDEX);

		setValue(0, position);
		setValue(1, file);
		setValue(2, epoch);
		setValue(3, inserts);
		setValue(4, updates);
		setValue(5, deletes);
		setValue(6, schemaops);
	}
}
