/**
 * This class is generated by jOOQ
 */
package cleandb.performance_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CondInstances extends org.jooq.impl.TableImpl<cleandb.performance_schema.tables.records.CondInstancesRecord> {

	private static final long serialVersionUID = 1392962638;

	/**
	 * The reference instance of <code>performance_schema.cond_instances</code>
	 */
	public static final cleandb.performance_schema.tables.CondInstances COND_INSTANCES = new cleandb.performance_schema.tables.CondInstances();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cleandb.performance_schema.tables.records.CondInstancesRecord> getRecordType() {
		return cleandb.performance_schema.tables.records.CondInstancesRecord.class;
	}

	/**
	 * The column <code>performance_schema.cond_instances.NAME</code>.
	 */
	public final org.jooq.TableField<cleandb.performance_schema.tables.records.CondInstancesRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>performance_schema.cond_instances.OBJECT_INSTANCE_BEGIN</code>.
	 */
	public final org.jooq.TableField<cleandb.performance_schema.tables.records.CondInstancesRecord, java.lang.Long> OBJECT_INSTANCE_BEGIN = createField("OBJECT_INSTANCE_BEGIN", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>performance_schema.cond_instances</code> table reference
	 */
	public CondInstances() {
		this("cond_instances", null);
	}

	/**
	 * Create an aliased <code>performance_schema.cond_instances</code> table reference
	 */
	public CondInstances(java.lang.String alias) {
		this(alias, cleandb.performance_schema.tables.CondInstances.COND_INSTANCES);
	}

	private CondInstances(java.lang.String alias, org.jooq.Table<cleandb.performance_schema.tables.records.CondInstancesRecord> aliased) {
		this(alias, aliased, null);
	}

	private CondInstances(java.lang.String alias, org.jooq.Table<cleandb.performance_schema.tables.records.CondInstancesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cleandb.performance_schema.PerformanceSchema.PERFORMANCE_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.performance_schema.tables.CondInstances as(java.lang.String alias) {
		return new cleandb.performance_schema.tables.CondInstances(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cleandb.performance_schema.tables.CondInstances rename(java.lang.String name) {
		return new cleandb.performance_schema.tables.CondInstances(name, null);
	}
}
