/**
 * This class is generated by jOOQ
 */
package cleandb.cleanrawdata.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Process extends org.jooq.impl.TableImpl<cleandb.cleanrawdata.tables.records.ProcessRecord> {

	private static final long serialVersionUID = 469507800;

	/**
	 * The reference instance of <code>CleanRawData.Process</code>
	 */
	public static final cleandb.cleanrawdata.tables.Process PROCESS = new cleandb.cleanrawdata.tables.Process();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cleandb.cleanrawdata.tables.records.ProcessRecord> getRecordType() {
		return cleandb.cleanrawdata.tables.records.ProcessRecord.class;
	}

	/**
	 * The column <code>CleanRawData.Process.ProcessInstanceID</code>.
	 */
	public final org.jooq.TableField<cleandb.cleanrawdata.tables.records.ProcessRecord, byte[]> PROCESSINSTANCEID = createField("ProcessInstanceID", org.jooq.impl.SQLDataType.BINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>CleanRawData.Process.SourceProcessInstanceID</code>.
	 */
	public final org.jooq.TableField<cleandb.cleanrawdata.tables.records.ProcessRecord, java.lang.String> SOURCEPROCESSINSTANCEID = createField("SourceProcessInstanceID", org.jooq.impl.SQLDataType.VARCHAR.length(30000).nullable(false), this, "");

	/**
	 * The column <code>CleanRawData.Process.ProcessModelID</code>.
	 */
	public final org.jooq.TableField<cleandb.cleanrawdata.tables.records.ProcessRecord, java.lang.String> PROCESSMODELID = createField("ProcessModelID", org.jooq.impl.SQLDataType.VARCHAR.length(30000).nullable(false), this, "");

	/**
	 * The column <code>CleanRawData.Process.ProcessName</code>.
	 */
	public final org.jooq.TableField<cleandb.cleanrawdata.tables.records.ProcessRecord, java.lang.String> PROCESSNAME = createField("ProcessName", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>CleanRawData.Process.StartTime</code>.
	 */
	public final org.jooq.TableField<cleandb.cleanrawdata.tables.records.ProcessRecord, java.sql.Timestamp> STARTTIME = createField("StartTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>CleanRawData.Process.EndTime</code>.
	 */
	public final org.jooq.TableField<cleandb.cleanrawdata.tables.records.ProcessRecord, java.sql.Timestamp> ENDTIME = createField("EndTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>CleanRawData.Process.Duration</code>.
	 */
	public final org.jooq.TableField<cleandb.cleanrawdata.tables.records.ProcessRecord, java.lang.Long> DURATION = createField("Duration", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>CleanRawData.Process.TrialID</code>.
	 */
	public final org.jooq.TableField<cleandb.cleanrawdata.tables.records.ProcessRecord, byte[]> TRIALID = createField("TrialID", org.jooq.impl.SQLDataType.BINARY.length(16).nullable(false), this, "");

	/**
	 * Create a <code>CleanRawData.Process</code> table reference
	 */
	public Process() {
		this("Process", null);
	}

	/**
	 * Create an aliased <code>CleanRawData.Process</code> table reference
	 */
	public Process(java.lang.String alias) {
		this(alias, cleandb.cleanrawdata.tables.Process.PROCESS);
	}

	private Process(java.lang.String alias, org.jooq.Table<cleandb.cleanrawdata.tables.records.ProcessRecord> aliased) {
		this(alias, aliased, null);
	}

	private Process(java.lang.String alias, org.jooq.Table<cleandb.cleanrawdata.tables.records.ProcessRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cleandb.cleanrawdata.Cleanrawdata.CLEANRAWDATA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cleandb.cleanrawdata.tables.records.ProcessRecord> getPrimaryKey() {
		return cleandb.cleanrawdata.Keys.KEY_PROCESS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cleandb.cleanrawdata.tables.records.ProcessRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cleandb.cleanrawdata.tables.records.ProcessRecord>>asList(cleandb.cleanrawdata.Keys.KEY_PROCESS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<cleandb.cleanrawdata.tables.records.ProcessRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<cleandb.cleanrawdata.tables.records.ProcessRecord, ?>>asList(cleandb.cleanrawdata.Keys.PROCESS_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.cleanrawdata.tables.Process as(java.lang.String alias) {
		return new cleandb.cleanrawdata.tables.Process(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cleandb.cleanrawdata.tables.Process rename(java.lang.String name) {
		return new cleandb.cleanrawdata.tables.Process(name, null);
	}
}
