/**
 * This class is generated by jOOQ
 */
package cleandb.mysql.tables;

/**
 * help categories
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HelpCategory extends org.jooq.impl.TableImpl<cleandb.mysql.tables.records.HelpCategoryRecord> {

	private static final long serialVersionUID = 242466144;

	/**
	 * The reference instance of <code>mysql.help_category</code>
	 */
	public static final cleandb.mysql.tables.HelpCategory HELP_CATEGORY = new cleandb.mysql.tables.HelpCategory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cleandb.mysql.tables.records.HelpCategoryRecord> getRecordType() {
		return cleandb.mysql.tables.records.HelpCategoryRecord.class;
	}

	/**
	 * The column <code>mysql.help_category.help_category_id</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.HelpCategoryRecord, org.jooq.types.UShort> HELP_CATEGORY_ID = createField("help_category_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>mysql.help_category.name</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.HelpCategoryRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>mysql.help_category.parent_category_id</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.HelpCategoryRecord, org.jooq.types.UShort> PARENT_CATEGORY_ID = createField("parent_category_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this, "");

	/**
	 * The column <code>mysql.help_category.url</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.HelpCategoryRecord, java.lang.String> URL = createField("url", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * Create a <code>mysql.help_category</code> table reference
	 */
	public HelpCategory() {
		this("help_category", null);
	}

	/**
	 * Create an aliased <code>mysql.help_category</code> table reference
	 */
	public HelpCategory(java.lang.String alias) {
		this(alias, cleandb.mysql.tables.HelpCategory.HELP_CATEGORY);
	}

	private HelpCategory(java.lang.String alias, org.jooq.Table<cleandb.mysql.tables.records.HelpCategoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private HelpCategory(java.lang.String alias, org.jooq.Table<cleandb.mysql.tables.records.HelpCategoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cleandb.mysql.Mysql.MYSQL, aliased, parameters, "help categories");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cleandb.mysql.tables.records.HelpCategoryRecord> getPrimaryKey() {
		return cleandb.mysql.Keys.KEY_HELP_CATEGORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cleandb.mysql.tables.records.HelpCategoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cleandb.mysql.tables.records.HelpCategoryRecord>>asList(cleandb.mysql.Keys.KEY_HELP_CATEGORY_PRIMARY, cleandb.mysql.Keys.KEY_HELP_CATEGORY_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.tables.HelpCategory as(java.lang.String alias) {
		return new cleandb.mysql.tables.HelpCategory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cleandb.mysql.tables.HelpCategory rename(java.lang.String name) {
		return new cleandb.mysql.tables.HelpCategory(name, null);
	}
}
