/**
 * This class is generated by jOOQ
 */
package cleandb.mysql.tables;

/**
 * Time zone transitions
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeZoneTransition extends org.jooq.impl.TableImpl<cleandb.mysql.tables.records.TimeZoneTransitionRecord> {

	private static final long serialVersionUID = 281366139;

	/**
	 * The reference instance of <code>mysql.time_zone_transition</code>
	 */
	public static final cleandb.mysql.tables.TimeZoneTransition TIME_ZONE_TRANSITION = new cleandb.mysql.tables.TimeZoneTransition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cleandb.mysql.tables.records.TimeZoneTransitionRecord> getRecordType() {
		return cleandb.mysql.tables.records.TimeZoneTransitionRecord.class;
	}

	/**
	 * The column <code>mysql.time_zone_transition.Time_zone_id</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.TimeZoneTransitionRecord, org.jooq.types.UInteger> TIME_ZONE_ID = createField("Time_zone_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>mysql.time_zone_transition.Transition_time</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.TimeZoneTransitionRecord, java.lang.Long> TRANSITION_TIME = createField("Transition_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mysql.time_zone_transition.Transition_type_id</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.TimeZoneTransitionRecord, org.jooq.types.UInteger> TRANSITION_TYPE_ID = createField("Transition_type_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * Create a <code>mysql.time_zone_transition</code> table reference
	 */
	public TimeZoneTransition() {
		this("time_zone_transition", null);
	}

	/**
	 * Create an aliased <code>mysql.time_zone_transition</code> table reference
	 */
	public TimeZoneTransition(java.lang.String alias) {
		this(alias, cleandb.mysql.tables.TimeZoneTransition.TIME_ZONE_TRANSITION);
	}

	private TimeZoneTransition(java.lang.String alias, org.jooq.Table<cleandb.mysql.tables.records.TimeZoneTransitionRecord> aliased) {
		this(alias, aliased, null);
	}

	private TimeZoneTransition(java.lang.String alias, org.jooq.Table<cleandb.mysql.tables.records.TimeZoneTransitionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cleandb.mysql.Mysql.MYSQL, aliased, parameters, "Time zone transitions");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cleandb.mysql.tables.records.TimeZoneTransitionRecord> getPrimaryKey() {
		return cleandb.mysql.Keys.KEY_TIME_ZONE_TRANSITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cleandb.mysql.tables.records.TimeZoneTransitionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cleandb.mysql.tables.records.TimeZoneTransitionRecord>>asList(cleandb.mysql.Keys.KEY_TIME_ZONE_TRANSITION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.tables.TimeZoneTransition as(java.lang.String alias) {
		return new cleandb.mysql.tables.TimeZoneTransition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cleandb.mysql.tables.TimeZoneTransition rename(java.lang.String name) {
		return new cleandb.mysql.tables.TimeZoneTransition(name, null);
	}
}
