/**
 * This class is generated by jOOQ
 */
package cleandb.mysql.tables;

/**
 * Time zones
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeZone extends org.jooq.impl.TableImpl<cleandb.mysql.tables.records.TimeZoneRecord> {

	private static final long serialVersionUID = -2102372221;

	/**
	 * The reference instance of <code>mysql.time_zone</code>
	 */
	public static final cleandb.mysql.tables.TimeZone TIME_ZONE = new cleandb.mysql.tables.TimeZone();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<cleandb.mysql.tables.records.TimeZoneRecord> getRecordType() {
		return cleandb.mysql.tables.records.TimeZoneRecord.class;
	}

	/**
	 * The column <code>mysql.time_zone.Time_zone_id</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.TimeZoneRecord, org.jooq.types.UInteger> TIME_ZONE_ID = createField("Time_zone_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>mysql.time_zone.Use_leap_seconds</code>.
	 */
	public final org.jooq.TableField<cleandb.mysql.tables.records.TimeZoneRecord, cleandb.mysql.enums.TimeZoneUseLeapSeconds> USE_LEAP_SECONDS = createField("Use_leap_seconds", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(cleandb.mysql.enums.TimeZoneUseLeapSeconds.class), this, "");

	/**
	 * Create a <code>mysql.time_zone</code> table reference
	 */
	public TimeZone() {
		this("time_zone", null);
	}

	/**
	 * Create an aliased <code>mysql.time_zone</code> table reference
	 */
	public TimeZone(java.lang.String alias) {
		this(alias, cleandb.mysql.tables.TimeZone.TIME_ZONE);
	}

	private TimeZone(java.lang.String alias, org.jooq.Table<cleandb.mysql.tables.records.TimeZoneRecord> aliased) {
		this(alias, aliased, null);
	}

	private TimeZone(java.lang.String alias, org.jooq.Table<cleandb.mysql.tables.records.TimeZoneRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, cleandb.mysql.Mysql.MYSQL, aliased, parameters, "Time zones");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<cleandb.mysql.tables.records.TimeZoneRecord, org.jooq.types.UInteger> getIdentity() {
		return cleandb.mysql.Keys.IDENTITY_TIME_ZONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<cleandb.mysql.tables.records.TimeZoneRecord> getPrimaryKey() {
		return cleandb.mysql.Keys.KEY_TIME_ZONE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<cleandb.mysql.tables.records.TimeZoneRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<cleandb.mysql.tables.records.TimeZoneRecord>>asList(cleandb.mysql.Keys.KEY_TIME_ZONE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public cleandb.mysql.tables.TimeZone as(java.lang.String alias) {
		return new cleandb.mysql.tables.TimeZone(alias, this);
	}

	/**
	 * Rename this table
	 */
	public cleandb.mysql.tables.TimeZone rename(java.lang.String name) {
		return new cleandb.mysql.tables.TimeZone(name, null);
	}
}
